import type { QuizBankQuestion } from "@/lib/quiz-question-bank";

/** OtĂˇzky s fotkou â€” pub ĂşroveĹ, nie detskĂ© rozpoznĂˇvanie. URL doplnĂ­Ĺˇ v editore. */
export const IMAGE_QUIZ_BANK: QuizBankQuestion[] = [
  {
    id: "img-01",
    body: "KtorĂ˝ herec je na fotke (v mladĹˇom veku, pred oscarovou slĂˇvou)?",
    answer: "Daniel Day-Lewis",
    options: [
      "Daniel Day-Lewis",
      "Gary Oldman",
      "Jeremy Irons",
      "Rupert Everett",
      "Colin Firth",
      "Ralph Fiennes",
    ],
    correctIndex: 0,
    difficulty: 8,
    note: "ZĂˇber z 80. rokov (napr. My Left Foot / A Room with a View). Bez typickĂ©ho vousu a s inĂ˝m stylingom vĂ¤ÄŤĹˇina netipuje â€” to je pointa.",
    tags: ["obrĂˇzok", "film", "celebrita"],
    isImageQuestion: true,
  },
  {
    id: "img-02",
    body: "KtorĂ˝ hrad je na fotke (vestavnĂ˝ do skalnej steny)?",
    answer: "PredjamskĂ˝ grad",
    options: [
      "PredjamskĂ˝ grad",
      "OravskĂ˝ hrad",
      "KarlĹˇtejn",
      "Loket",
      "Ojcowski zĂˇmok",
      "DevĂ­n",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "Slovinsko â€” vstupnĂˇ jama v skale, most pred fasĂˇdou. Orava je obÄľĂşbenĂˇ pasca, ale ten grad visĂ­ priamo v stene.",
    tags: ["obrĂˇzok", "hrad", "eurĂłpa"],
    isImageQuestion: true,
  },
  {
    id: "img-03",
    body: "KtorĂ˝ model auta je na fotke (francĂşzska ikona 50.â€“60. rokov)?",
    answer: "CitroĂ«n DS",
    options: ["CitroĂ«n DS", "Peugeot 404", "Renault 16", "CitroĂ«n 2CV", "Panhard", "Simca 1300"],
    correctIndex: 0,
    difficulty: 7,
    note: "AerodynamickĂˇ silueta, jedno kolesnĂ© oblĂşky, ÄŤasto v bielej. DS = â€ždĂ©esseâ€ś (bohyĹa). Nie je to beĹľnĂ© auto z ulice dnes.",
    tags: ["obrĂˇzok", "auto", "histĂłria"],
    isImageQuestion: true,
  },
  {
    id: "img-04",
    body: "KtorĂ© mesto je na fotke (historickĂ© centrum pri rieke, nie Praha)?",
    answer: "ÄŚeskĂ˝ Krumlov",
    options: ["ÄŚeskĂ˝ Krumlov", "Praha", "TelÄŤ", "TĹ™eboĹ", "KutnĂˇ Hora", "Bratislava"],
    correctIndex: 0,
    difficulty: 7,
    note: "ZĂˇmok na skale nad zĂˇhybom Vltavy, ÄŤervenĂ© strechy. Pub pasca: vyzerĂˇ ako â€žmalĂˇ Prahaâ€ś, ale je to Krumlov.",
    tags: ["obrĂˇzok", "mesto", "ÄŤesko"],
    isImageQuestion: true,
  },
  {
    id: "img-05",
    body: "KtorĂ© zviera je na fotke (prĂşĹľkovanĂ© nohy, tmavĂ© telo, konĹľskĂ© pralesy)?",
    answer: "Okapi",
    options: ["Okapi", "Zebra", "TapĂ­r", "Antilopa bongo", "PralesnĂ˝ kĂ´Ĺ", "Gnu"],
    correctIndex: 0,
    difficulty: 8,
    note: "PrĂ­buznĂ˝ girafy, ale vyzerĂˇ ako zebra + antilopa. V zoo (Praha, ViedeĹ) Ăˇno â€” v prĂ­rode ho beĹľnĂ˝ ÄŤlovek nevidĂ­.",
    tags: ["obrĂˇzok", "zvieratĂˇ", "veda"],
    isImageQuestion: true,
  },
  {
    id: "img-06",
    body: "KtorĂˇ stavba je na fotke (detail fasĂˇdy, katalĂˇnsky modernizmus)?",
    answer: "Casa BatllĂł",
    options: ["Casa BatllĂł", "Sagrada FamĂ­lia", "Casa MilĂ ", "Palau GĂĽell", "Expiatori del Tibidabo", "Palau de la MĂşsica"],
    correctIndex: 0,
    difficulty: 8,
    note: "GaudĂ­ho â€žkostra drakaâ€ś â€” masky balkĂłnov, mozaika, modrĂ© dlaĹľdice. Sagrada je pasca, ale BatllĂł mĂˇ charakteristickĂ© balkĂłny.",
    tags: ["obrĂˇzok", "architektĂşra", "Ĺˇpanielsko"],
    isImageQuestion: true,
  },
  {
    id: "img-07",
    body: "KtorĂ˝ futbalista je na fotke (slĂˇvny â€žkrĂˇÄľovskĂ˝â€ś kop v 90. rokoch)?",
    answer: "Eric Cantona",
    options: [
      "Eric Cantona",
      "David Beckham",
      "Eric Gerets",
      "Paolo Di Canio",
      "Roy Keane",
      "Gianluca Vialli",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "Manchester United, golman padĂˇ, Cantona letĂ­ â€” ikonickĂ˝ moment. Beckham je bezpeÄŤnĂ˝ faloĹˇnĂ˝ tip.",
    tags: ["obrĂˇzok", "Ĺˇport", "futbal"],
    isImageQuestion: true,
  },
  {
    id: "img-08",
    body: "KtorĂˇ znaÄŤka je na logu (netopier, alkohol)?",
    answer: "Bacardi",
    options: ["Bacardi", "Captain Morgan", "Havana Club", "Malibu", "Smirnoff", "JĂ¤germeister"],
    correctIndex: 0,
    difficulty: 6,
    note: "Netopier na etikete â€” orezanĂ˝ detail bez textu. Captain Morgan mĂˇ pirĂˇta, Bacardi netopiera.",
    tags: ["obrĂˇzok", "logo", "kultĂşra"],
    isImageQuestion: true,
  },
  {
    id: "img-09",
    body: "KtorĂ˝ most je na fotke (oblĂşk cez Neretvu, Bosna a Hercegovina)?",
    answer: "Stari most (Mostar)",
    options: [
      "Stari most (Mostar)",
      "Most Karla IV.",
      "Rialto",
      "Pont du Gard",
      "Charles Bridge",
      "Puente Nuevo (Ronda)",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "TenkĂ˝ kamennĂ˝ oblĂşk, minarety v pozadĂ­. Po vojne znovu postavenĂ˝ â€” typickĂ˝ zĂˇber z Mostaru.",
    tags: ["obrĂˇzok", "architektĂşra", "balkĂˇn"],
    isImageQuestion: true,
  },
  {
    id: "img-10",
    body: "KtorĂ˝ hudobnĂ­k je na fotke (The Boss, Ă©ra Born to Run)?",
    answer: "Bruce Springsteen",
    options: [
      "Bruce Springsteen",
      "Bob Seger",
      "Tom Petty",
      "Bryan Adams",
      "John Mellencamp",
      "Billy Joel",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "MladĂ˝ Springsteen s gitĂˇrou â€” nie ikonickĂ˝ starnĂşci Bruce. Pub tĂ­m poznĂˇ meno, ale mladĂş tvĂˇr menej.",
    tags: ["obrĂˇzok", "hudba", "rock"],
    isImageQuestion: true,
  },
  {
    id: "img-11",
    body: "KtorĂ© jedlo je na fotke (Peru, surovĂ© ryby v kyslej limetke)?",
    answer: "Ceviche",
    options: ["Ceviche", "Poke", "Tartare", "Gravlax", "Aguachile", "Kinilaw"],
    correctIndex: 0,
    difficulty: 7,
    note: "Biele ryby, cibuÄľa, koriander, limetka â€” nie sushi. Poke je havajskĂˇ pasca.",
    tags: ["obrĂˇzok", "jedlo", "svet"],
    isImageQuestion: true,
  },
  {
    id: "img-12",
    body: "KtorĂ˝ prĂ­stroj je na fotke (Ĺˇifrovacia maĹˇina z 2. svetovej vojny)?",
    answer: "EnigmovĂˇ maĹˇina",
    options: [
      "EnigmovĂˇ maĹˇina",
      "Lorenz SZ40",
      "Telegraf Morse",
      "DifferenciĂˇlny analyzĂˇtor",
      "PĂ­sacĂ­ stroj Underwood",
      "MagnetofĂłn",
    ],
    correctIndex: 0,
    difficulty: 8,
    note: "Rotory, klĂˇvesnica, drevenĂ© krabice â€” mĂşzeum Bletchley Park alebo replika. Nie beĹľnĂ˝ predmet.",
    tags: ["obrĂˇzok", "histĂłria", "technolĂłgie"],
    isImageQuestion: true,
  },
  {
    id: "img-13",
    body: "KtorĂˇ monumentĂˇlna skulptĂşra je na fotke (4 hlavy v skale, USA)?",
    answer: "Mount Rushmore",
    options: [
      "Mount Rushmore",
      "Stone Mountain",
      "Crazy Horse Memorial",
      "Mount Nemrut",
      "Budha v Leshan",
      "El CapitĂˇn (Yosemite)",
    ],
    correctIndex: 0,
    difficulty: 6,
    note: "Washington, Jefferson, Roosevelt, Lincoln â€” zĂˇber z diaÄľky alebo z profilu. Socha slobody je prĂ­liĹˇ ÄľahkĂˇ pasca.",
    tags: ["obrĂˇzok", "architektĂşra", "usa"],
    isImageQuestion: true,
  },
  {
    id: "img-14",
    body: "KtorĂ© lietadlo je na fotke (ÄŤierne prieskumnĂ©, rekord rĂ˝chlosti)?",
    answer: "Lockheed SR-71 Blackbird",
    options: [
      "Lockheed SR-71 Blackbird",
      "Concorde",
      "U-2 Dragon Lady",
      "MiG-25",
      "F-117 Nighthawk",
      "North American X-15",
    ],
    correctIndex: 0,
    difficulty: 9,
    note: "Matte ÄŤierne, ostrĂ© delty, dvojitĂ© kokpity. Concorde je civilnĂˇ pasca â€” Blackbird je armĂˇdny ĹˇpiĂłn.",
    tags: ["obrĂˇzok", "letectvo", "histĂłria"],
    isImageQuestion: true,
  },
  {
    id: "img-15",
    body: "KtorĂ˝ ostrovnĂ˝ regiĂłn je na fotke (trĂˇvou pokrytĂ© strechy, ovce, sever)?",
    answer: "FaerskĂ© ostrovy",
    options: [
      "FaerskĂ© ostrovy",
      "Island",
      "Shetlandy",
      "Lofoty",
      "GrĂłnsko",
      "Skye (Ĺ kĂłtsko)",
    ],
    correctIndex: 0,
    difficulty: 8,
    note: "TypickĂ© domy so zelenĂ˝mi strechami, Ăşzke fjordy, sivĂ© ovce. Island mĂˇ viac lavy a menej trĂˇvovĂ˝ch striech.",
    tags: ["obrĂˇzok", "geografia", "eurĂłpa"],
    isImageQuestion: true,
  },
  {
    id: "img-16",
    body: "KtorĂˇ filmovĂˇ postava v grime je na fotke (nemĂ˝ horor 1922)?",
    answer: "Nosferatu (Count Orlok)",
    options: [
      "Nosferatu (Count Orlok)",
      "Dracula (Bela Lugosi)",
      "Frankensteinov netvor",
      "Freddy Krueger",
      "Pennywise",
      "FantĂłm opery",
    ],
    correctIndex: 0,
    difficulty: 8,
    note: "Max Schreck â€” ĹˇpicatĂ© uĹˇi, dlhĂ© prsty, kostra tvĂˇr. Nie modernĂ˝ Dracula â€” expresionistickĂ˝ klasik Murnaua.",
    tags: ["obrĂˇzok", "film", "horor"],
    isImageQuestion: true,
  },
  {
    id: "img-17",
    body: "KtorĂ© rally auto je na fotke (WRC legenda, Lancia)?",
    answer: "Lancia Delta Integrale",
    options: [
      "Lancia Delta Integrale",
      "Lancia Stratos",
      "Ford Escort RS Cosworth",
      "Subaru Impreza WRX",
      "Audi Quattro S1",
      "Peugeot 205 T16",
    ],
    correctIndex: 0,
    difficulty: 8,
    note: "Boxy hatchback, Martini / Alitalia livery, Ĺˇtyri svetlĂˇ vpredu. Stratos mĂˇ klinovĂ˝ tvar â€” inĂˇ generĂˇcia.",
    tags: ["obrĂˇzok", "auto", "Ĺˇport"],
    isImageQuestion: true,
  },
  {
    id: "img-18",
    body: "KtorĂ˝ zĂˇmok je na fotke (anglickĂ˝ novogotickĂ˝ ĹˇtĂ˝l, juh ÄŚech)?",
    answer: "HlubokĂˇ nad Vltavou",
    options: [
      "HlubokĂˇ nad Vltavou",
      "Neuschwanstein",
      "Windsor",
      "KonopiĹˇtÄ›",
      "ÄŚervenĂˇ Lhota",
      "Lednice",
    ],
    correctIndex: 0,
    difficulty: 8,
    note: "Bielo-ÄŤervenĂ© cihly, veĹľe, anglickĂ˝ park. Neuschwanstein je biely rozprĂˇvkovĂ˝ â€” HlubokĂˇ je tmavĹˇĂ­, gotickejĹˇĂ­.",
    tags: ["obrĂˇzok", "hrad", "ÄŤesko"],
    isImageQuestion: true,
  },
  {
    id: "img-19",
    body: "KtorĂ˝ Ĺˇport je na fotke (kovovĂ© gule, Ĺˇtrk, Provence)?",
    answer: "PĂ©tanque",
    options: ["PĂ©tanque", "Boccia", "Curling", "Bowling na trĂˇvniku", "Shuffleboard", "Kroket"],
    correctIndex: 0,
    difficulty: 7,
    note: "HrĂˇÄŤi v tĂ­sku, malĂ© kovovĂ© gule, cochonnet. Nie Äľad ako curling â€” provence atmosfĂ©ra.",
    tags: ["obrĂˇzok", "Ĺˇport", "francĂşzsko"],
    isImageQuestion: true,
  },
  {
    id: "img-20",
    body: "KtorĂˇ slovenskĂˇ bankovka je na fotke (1993â€“2008, portrĂ©t Ä˝. Ĺ tĂşra)?",
    answer: "500 Sk",
    options: ["500 Sk", "200 Sk", "1000 Sk", "5000 Sk", "100 Sk", "20 Sk"],
    correctIndex: 0,
    difficulty: 7,
    note: "ZelenkavĂˇ, Ä˝udovĂ­t Ĺ tĂşr vpredu. 1000 Sk mĂˇ Mateja Bela â€” pub generĂˇcia eĹˇte pamĂ¤tĂˇ koruny.",
    tags: ["obrĂˇzok", "histĂłria", "slovensko"],
    isImageQuestion: true,
  },
];
