import type { QuizBankQuestion } from "@/lib/quiz-question-bank";

/** Otázky s fotkou — pub úroveň. URL doplníš v editore. */
export const IMAGE_QUIZ_BANK: QuizBankQuestion[] = [
  {
    id: "img-01",
    body: "Ktorý herec je na fotke (v mladšom veku, pred oscarovou slávou)?",
    answer: "Daniel Day-Lewis",
    options: [
      "Daniel Day-Lewis",
      "Gary Oldman",
      "Jeremy Irons",
      "Rupert Everett",
      "Colin Firth",
      "Ralph Fiennes",
    ],
    correctIndex: 0,
    difficulty: 8,
    note: "Záber z 80. rokov (napr. My Left Foot / A Room with a View). Bez typického vousu a s iným stylingom väčšina netipuje — to je pointa.",
    tags: ["obrázok", "film", "celebrita"],
    isImageQuestion: true,
  },
  {
    id: "img-02",
    body: "Ktorý hrad je na fotke (vestavný do skalnej steny)?",
    answer: "Predjamský grad",
    options: [
      "Predjamský grad",
      "Oravský hrad",
      "Karlštejn",
      "Loket",
      "Ojcowski zámok",
      "Devín",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "Slovinsko — vstupná jama v skale, most pred fasádou. Orava je obľúbená pasca, ale ten grad visí priamo v stene.",
    tags: ["obrázok", "hrad", "slovinsko"],
    isImageQuestion: true,
  },
  {
    id: "img-03",
    body: "Ktorý model auta je na fotke (francúzska ikona 50.–60. rokov)?",
    answer: "Citroën DS",
    options: ["Citroën DS", "Peugeot 404", "Renault 16", "Citroën 2CV", "Panhard", "Simca 1300"],
    correctIndex: 0,
    difficulty: 7,
    note: "Aerodynamická silueta, jedno kolesné oblúky, často v bielej. DS = „déesse“ (bohyňa). Nie je to bežné auto z ulice dnes.",
    tags: ["obrázok", "auto", "francúzsko"],
    isImageQuestion: true,
  },
  {
    id: "img-04",
    body: "Ktoré mesto je na fotke (historické centrum pri rieke, nie Praha)?",
    answer: "Český Krumlov",
    options: ["Český Krumlov", "Praha", "Telč", "Třeboň", "Kutná Hora", "Bratislava"],
    correctIndex: 0,
    difficulty: 7,
    note: "Zámok na skale nad záhybom Vltavy, červené strechy. Pub pasca: vyzerá ako „malá Praha“, ale je to Krumlov.",
    tags: ["obrázok", "mesto", "česko"],
    isImageQuestion: true,
  },
  {
    id: "img-05",
    body: "Ktoré zviera je na fotke (prúžkované nohy, tmavé telo, konžské pralesy)?",
    answer: "Okapi",
    options: ["Okapi", "Zebra", "Tapír", "Antilopa bongo", "Pralesný kôň", "Gnu"],
    correctIndex: 0,
    difficulty: 8,
    note: "Príbuzný girafy, ale vyzerá ako zebra + antilopa. V zoo (Praha, Viedeň) áno — v prírode ho bežný človek nevidí.",
    tags: ["obrázok", "zvieratá", "afrika"],
    isImageQuestion: true,
  },
  {
    id: "img-06",
    body: "Ktorá stavba je na fotke (detail fasády, katalánsky modernizmus)?",
    answer: "Casa Batlló",
    options: ["Casa Batlló", "Sagrada Família", "Casa Milà", "Palau Güell", "Expiatori del Tibidabo", "Palau de la Música"],
    correctIndex: 0,
    difficulty: 8,
    note: "Gaudího „kostra draka“ — masky balkónov, mozaika, modré dlaždice. Sagrada je pasca, ale Batlló má charakteristické balkóny.",
    tags: ["obrázok", "architektúra", "španielsko"],
    isImageQuestion: true,
  },
  {
    id: "img-07",
    body: "Ktorý futbalista je na fotke (slávny „kráľovský“ kop v 90. rokoch)?",
    answer: "Eric Cantona",
    options: [
      "Eric Cantona",
      "David Beckham",
      "Eric Gerets",
      "Paolo Di Canio",
      "Roy Keane",
      "Gianluca Vialli",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "Manchester United, golman padá, Cantona letí — ikonický moment. Beckham je bezpečný falošný tip.",
    tags: ["obrázok", "futbal", "anglicko"],
    isImageQuestion: true,
  },
  {
    id: "img-08",
    body: "Ktorá značka je na logu (netopier, alkohol)?",
    answer: "Bacardi",
    options: ["Bacardi", "Captain Morgan", "Havana Club", "Malibu", "Smirnoff", "Jägermeister"],
    correctIndex: 0,
    difficulty: 6,
    note: "Netopier na etikete — detail bez textu. Captain Morgan má piráta, Bacardi netopiera.",
    tags: ["obrázok", "logo", "alkohol"],
    isImageQuestion: true,
  },
  {
    id: "img-09",
    body: "Ktorý most je na fotke (oblúk cez Neretvu, Bosna a Hercegovina)?",
    answer: "Stari most (Mostar)",
    options: [
      "Stari most (Mostar)",
      "Most Karla IV.",
      "Rialto",
      "Pont du Gard",
      "Charles Bridge",
      "Puente Nuevo (Ronda)",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "Tenký kamenný oblúk, minarety v pozadí. Po vojne znovu postavený — typický záber z Mostaru.",
    tags: ["obrázok", "most", "balkán"],
    isImageQuestion: true,
  },
  {
    id: "img-10",
    body: "Ktorý hudobník je na fotke (The Boss, éra Born to Run)?",
    answer: "Bruce Springsteen",
    options: [
      "Bruce Springsteen",
      "Bob Seger",
      "Tom Petty",
      "Bryan Adams",
      "John Mellencamp",
      "Billy Joel",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "Mladý Springsteen s gitárou — nie ikonický starnúci Bruce. Pub tím pozná meno, ale mladú tvár menej.",
    tags: ["obrázok", "hudba", "rock"],
    isImageQuestion: true,
  },
  {
    id: "img-11",
    body: "Ktoré jedlo je na fotke (Peru, surové ryby v kyslej limetke)?",
    answer: "Ceviche",
    options: ["Ceviche", "Poke", "Tartare", "Gravlax", "Aguachile", "Kinilaw"],
    correctIndex: 0,
    difficulty: 7,
    note: "Biele ryby, cibuľa, koriander, limetka — nie sushi. Poke je havajská pasca.",
    tags: ["obrázok", "jedlo", "peru"],
    isImageQuestion: true,
  },
  {
    id: "img-12",
    body: "Ktorý prístroj je na fotke (šifrovacia mašina z 2. svetovej vojny)?",
    answer: "Enigmová mašina",
    options: [
      "Enigmová mašina",
      "Lorenz SZ40",
      "Telegraf Morse",
      "Differenciálny analyzátor",
      "Písací stroj Underwood",
      "Magnetofón",
    ],
    correctIndex: 0,
    difficulty: 8,
    note: "Rotory, klávesnica, drevené krabice — múzeum Bletchley Park alebo replika. Nie bežný predmet.",
    tags: ["obrázok", "história", "technológie"],
    isImageQuestion: true,
  },
  {
    id: "img-13",
    body: "Ktorá monumentálna skulptúra je na fotke (4 hlavy v skale, USA)?",
    answer: "Mount Rushmore",
    options: [
      "Mount Rushmore",
      "Stone Mountain",
      "Crazy Horse Memorial",
      "Mount Nemrut",
      "Budha v Leshan",
      "El Capitán (Yosemite)",
    ],
    correctIndex: 0,
    difficulty: 6,
    note: "Washington, Jefferson, Roosevelt, Lincoln — záber z diaľky alebo z profilu. Socha slobody je príliš ľahká pasca.",
    tags: ["obrázok", "socha", "usa"],
    isImageQuestion: true,
  },
  {
    id: "img-14",
    body: "Ktoré lietadlo je na fotke (čierne prieskumné, rekord rýchlosti)?",
    answer: "Lockheed SR-71 Blackbird",
    options: [
      "Lockheed SR-71 Blackbird",
      "Concorde",
      "U-2 Dragon Lady",
      "MiG-25",
      "F-117 Nighthawk",
      "North American X-15",
    ],
    correctIndex: 0,
    difficulty: 9,
    note: "Matte čierne, ostré delty, dvojité kokpity. Concorde je civilná pasca — Blackbird je armádny špión.",
    tags: ["obrázok", "letectvo", "usa"],
    isImageQuestion: true,
  },
  {
    id: "img-15",
    body: "Ktorý ostrovný región je na fotke (trávou pokryté strechy, ovce, sever)?",
    answer: "Faerské ostrovy",
    options: [
      "Faerské ostrovy",
      "Island",
      "Shetlandy",
      "Lofoty",
      "Grónsko",
      "Skye (Škótsko)",
    ],
    correctIndex: 0,
    difficulty: 8,
    note: "Typické domy so zelenými strechami, úzke fjordy, sivé ovce. Island má viac lavy a menej trávových striech.",
    tags: ["obrázok", "geografia", "faerské ostrovy"],
    isImageQuestion: true,
  },
  {
    id: "img-16",
    body: "Ktorá filmová postava v grime je na fotke (nemý horor 1922)?",
    answer: "Nosferatu (Count Orlok)",
    options: [
      "Nosferatu (Count Orlok)",
      "Dracula (Bela Lugosi)",
      "Frankensteinov netvor",
      "Freddy Krueger",
      "Pennywise",
      "Fantóm opery",
    ],
    correctIndex: 0,
    difficulty: 8,
    note: "Max Schreck — špicaté uši, dlhé prsty, kostra tvár. Nie moderný Dracula — expresionistický klasik Murnaua.",
    tags: ["obrázok", "film", "horor"],
    isImageQuestion: true,
  },
  {
    id: "img-17",
    body: "Ktoré rally auto je na fotke (WRC legenda, Lancia)?",
    answer: "Lancia Delta Integrale",
    options: [
      "Lancia Delta Integrale",
      "Lancia Stratos",
      "Ford Escort RS Cosworth",
      "Subaru Impreza WRX",
      "Audi Quattro S1",
      "Peugeot 205 T16",
    ],
    correctIndex: 0,
    difficulty: 8,
    note: "Boxy hatchback, Martini / Alitalia livery, štyri svetlá vpredu. Stratos má klinový tvar — iná generácia.",
    tags: ["obrázok", "auto", "rally"],
    isImageQuestion: true,
  },
  {
    id: "img-18",
    body: "Ktorý zámok je na fotke (anglický novogotický štýl, juh Čech)?",
    answer: "Hluboká nad Vltavou",
    options: [
      "Hluboká nad Vltavou",
      "Neuschwanstein",
      "Windsor",
      "Konopiště",
      "Červená Lhota",
      "Lednice",
    ],
    correctIndex: 0,
    difficulty: 8,
    note: "Bielo-červené cihly, veže, anglický park. Neuschwanstein je biely rozprávkový — Hluboká je tmavší, gotickejší.",
    tags: ["obrázok", "hrad", "česko"],
    isImageQuestion: true,
  },
  {
    id: "img-19",
    body: "Ktorý šport je na fotke (kovové gule, štrk, Provence)?",
    answer: "Pétanque",
    options: ["Pétanque", "Boccia", "Curling", "Bowling na trávniku", "Shuffleboard", "Kroket"],
    correctIndex: 0,
    difficulty: 7,
    note: "Hráči v tísku, malé kovové gule, cochonnet. Nie ľad ako curling — provence atmosféra.",
    tags: ["obrázok", "šport", "francúzsko"],
    isImageQuestion: true,
  },
  {
    id: "img-20",
    body: "Ktorá slovenská bankovka je na fotke (1993–2008, portrét Ľ. Štúra)?",
    answer: "500 Sk",
    options: ["500 Sk", "200 Sk", "1000 Sk", "5000 Sk", "100 Sk", "20 Sk"],
    correctIndex: 0,
    difficulty: 7,
    note: "Zelenkavá, Ľudovít Štúr vpredu. 1000 Sk má Mateja Bela — pub generácia ešte pamätá koruny.",
    tags: ["obrázok", "história", "slovensko"],
    isImageQuestion: true,
  },
];
