import type { QuizBankQuestion } from "@/lib/quiz-question-bank";

/** Otázky s fotkou — URL doplníš v editore po vložení. */
export const IMAGE_QUIZ_BANK: QuizBankQuestion[] = [
  {
    id: "img-01",
    body: "Ktorá celebrita je na fotke?",
    answer: "Morgan Freeman",
    options: ["Morgan Freeman", "Samuel L. Jackson", "Denzel Washington", "Will Smith", "Idris Elba", "Forest Whitaker"],
    correctIndex: 0,
    difficulty: 4,
    note: "Portrét z profilu alebo z červeného koberca. Stačí rozpoznateľná tvár — netreba extrémny detail.",
    tags: ["obrázok", "celebrita", "film"],
    isImageQuestion: true,
    imageHint: "Portrét Morgan Freemana",
  },
  {
    id: "img-02",
    body: "Ktorý slovenský hrad je na fotke?",
    answer: "Oravský hrad",
    options: ["Oravský hrad", "Bojnický hrad", "Spišský hrad", "Devín", "Trenčiansky hrad", "Bratislavský hrad"],
    correctIndex: 0,
    difficulty: 5,
    note: "Typický záber z údolia — skala, most, vysoká veža. Orava je v pub kvíze klasika.",
    tags: ["obrázok", "hrad", "slovensko"],
    isImageQuestion: true,
    imageHint: "Oravský hrad z údolia",
  },
  {
    id: "img-03",
    body: "Ktoré auto je na fotke?",
    answer: "DeLorean DMC-12",
    options: ["DeLorean DMC-12", "Volkswagen Beetle", "Mini Cooper", "Ford Mustang", "Porsche 911", "Fiat 500"],
    correctIndex: 0,
    difficulty: 5,
    note: "Nerezové karosérie a gullwing dvere — Back to the Future ikona. Beetle je tiež dobrá pasca.",
    tags: ["obrázok", "auto", "film"],
    isImageQuestion: true,
    imageHint: "DeLorean — strieborné, gullwing dvere",
  },
  {
    id: "img-04",
    body: "Ktoré mesto je na fotke?",
    answer: "Praha",
    options: ["Praha", "Budapešť", "Viedeň", "Krakov", "Bratislava", "Salzburg"],
    correctIndex: 0,
    difficulty: 4,
    note: "Karlov most + Pražský hrad, alebo Orloj. V pub kvíze funguje aj nočný panorama.",
    tags: ["obrázok", "mesto", "európa"],
    isImageQuestion: true,
    imageHint: "Praha — most alebo panorama",
  },
  {
    id: "img-05",
    body: "Ktoré zviera je na fotke?",
    answer: "Panda veľká",
    options: ["Panda veľká", "Koala", "Lev", "Leopard", "Medveď hnedý", "Vlk"],
    correctIndex: 0,
    difficulty: 3,
    note: "Čierno-biela panda s bambúsom — okamžite rozpoznateľná. Koala je obľúbený falošný tip.",
    tags: ["obrázok", "zvieratá", "príroda"],
    isImageQuestion: true,
    imageHint: "Panda veľká",
  },
  {
    id: "img-06",
    body: "Ktorá svetoznáma stavba je na fotke?",
    answer: "Eiffelova veža",
    options: ["Eiffelova veža", "Big Ben", "Koloseum", "Pisa", "Empire State Building", "Sagrada Família"],
    correctIndex: 0,
    difficulty: 3,
    note: "Stačí silueta — netreba celý Champ de Mars. Môže byť detail alebo nočné osvetlenie.",
    tags: ["obrázok", "architektúra", "francúzsko"],
    isImageQuestion: true,
    imageHint: "Eiffelova veža",
  },
  {
    id: "img-07",
    body: "Ktorý futbalista je na fotke?",
    answer: "Lionel Messi",
    options: ["Lionel Messi", "Cristiano Ronaldo", "Neymar", "Kylian Mbappé", "Robert Lewandowski", "Erling Haaland"],
    correctIndex: 0,
    difficulty: 4,
    note: "V drese Argentíny, Barcelony, Inter Miami alebo PSG — Messi vs Ronaldo je pub klasika.",
    tags: ["obrázok", "šport", "futbal"],
    isImageQuestion: true,
    imageHint: "Lionel Messi v drese",
  },
  {
    id: "img-08",
    body: "Ktorá značka je na logu?",
    answer: "Apple",
    options: ["Apple", "Samsung", "Google", "Microsoft", "Sony", "Huawei"],
    correctIndex: 0,
    difficulty: 3,
    note: "Jablko s odhryznutím — funguje aj bez textu pod logom. Skús orezaný detail, nie celý telefón.",
    tags: ["obrázok", "logo", "technológie"],
    isImageQuestion: true,
    imageHint: "Logo Apple — jablko",
  },
  {
    id: "img-09",
    body: "Ktorý most je na fotke?",
    answer: "Golden Gate Bridge",
    options: ["Golden Gate Bridge", "Brooklyn Bridge", "Tower Bridge", "Most Karla IV.", "Rialto", "Most v Sydney"],
    correctIndex: 0,
    difficulty: 5,
    note: "Červeno-oranžový most v San Franciscu v hmle — jeden z najikonickejších záberov sveta.",
    tags: ["obrázok", "architektúra", "usa"],
    isImageQuestion: true,
    imageHint: "Golden Gate Bridge",
  },
  {
    id: "img-10",
    body: "Ktorý hudobník je na fotke?",
    answer: "Freddie Mercury",
    options: ["Freddie Mercury", "Elvis Presley", "David Bowie", "Mick Jagger", "John Lennon", "Prince"],
    correctIndex: 0,
    difficulty: 5,
    note: "Queen frontman — často v bielej trenčke na Live Aid alebo s mikrofónom. Veľmi rozpoznateľný.",
    tags: ["obrázok", "hudba", "celebrita"],
    isImageQuestion: true,
    imageHint: "Freddie Mercury — Queen",
  },
  {
    id: "img-11",
    body: "Ktoré jedlo je na fotke?",
    answer: "Sushi",
    options: ["Sushi", "Pizza", "Tacos", "Paella", "Pho", "Ramen"],
    correctIndex: 0,
    difficulty: 3,
    note: "Maki alebo nigiri na drevenej doske — sushi vs ramen je dobrá diskusia pri stole.",
    tags: ["obrázok", "jedlo", "kultúra"],
    isImageQuestion: true,
    imageHint: "Sushi — maki alebo nigiri",
  },
  {
    id: "img-12",
    body: "Ktorý predmet je na fotke?",
    answer: "Rubikova kocka",
    options: ["Rubikova kocka", "Šach", "Lego kocka", "Jojo", "Kendama", "Domino"],
    correctIndex: 0,
    difficulty: 4,
    note: "3×3 farebná kocka — funguje aj mierne rozbitá alebo v ruke. Názov je maďarský vynálezca Ernő Rubik.",
    tags: ["obrázok", "predmet", "hry"],
    isImageQuestion: true,
    imageHint: "Rubikova kocka 3×3",
  },
  {
    id: "img-13",
    body: "Ktorá slávna socha je na fotke?",
    answer: "Socha slobody",
    options: ["Socha slobody", "Christ the Redeemer", "Mavka", "David", "Mys Mykonos", "Bratislavský Meštiansky park"],
    correctIndex: 0,
    difficulty: 4,
    note: "New York — pochodeň, koruna, zelená patina. Môže byť z lode alebo z Ellis Island.",
    tags: ["obrázok", "architektúra", "usa"],
    isImageQuestion: true,
    imageHint: "Socha slobody, New York",
  },
  {
    id: "img-14",
    body: "Ktoré lietadlo je na fotke?",
    answer: "Concorde",
    options: ["Concorde", "Boeing 747", "Airbus A380", "Spitfire", "MiG-21", "Cessna 172"],
    correctIndex: 0,
    difficulty: 7,
    note: "Supersonický nos a delta krídla — Concorde je pub pasca, lebo väčšina tipuje bežný airliner.",
    tags: ["obrázok", "letectvo", "technológie"],
    isImageQuestion: true,
    imageHint: "Concorde — delta krídla",
  },
  {
    id: "img-15",
    body: "Ktorá krajina je na fotke (krajina)?",
    answer: "Island",
    options: ["Island", "Nórsko", "Nový Zéland", "Grónsko", "Faerské ostrovy", "Škótsko"],
    correctIndex: 0,
    difficulty: 6,
    note: "Čierna láva, zelený mach, vodopády, možno aurora. Island vs Nórsko je ťažký, ale dobrý pub háčik.",
    tags: ["obrázok", "geografia", "príroda"],
    isImageQuestion: true,
    imageHint: "Island — krajina, vodopád alebo aurora",
  },
  {
    id: "img-16",
    body: "Ktorá filmová postava je na fotke?",
    answer: "Darth Vader",
    options: ["Darth Vader", "Batman", "Iron Man", "Spider-Man", "Joker", "Gandalf"],
    correctIndex: 0,
    difficulty: 4,
    note: "Čierna helma a plášť — Star Wars. Funguje cosplay aj oficiálny still z filmu.",
    tags: ["obrázok", "film", "kultúra"],
    isImageQuestion: true,
    imageHint: "Darth Vader — helma",
  },
  {
    id: "img-17",
    body: "Ktorá automobilka je na logu?",
    answer: "Ferrari",
    options: ["Ferrari", "Lamborghini", "Porsche", "BMW", "Mercedes-Benz", "Audi"],
    correctIndex: 0,
    difficulty: 5,
    note: "Vrúcajúci kôň na žltom pozadí — Ferrari vs Lamborghini býva tesné.",
    tags: ["obrázok", "auto", "logo"],
    isImageQuestion: true,
    imageHint: "Logo Ferrari — kôň",
  },
  {
    id: "img-18",
    body: "Ktorý zámok je na fotke?",
    answer: "Neuschwanstein",
    options: ["Neuschwanstein", "Versailles", "Windsor", "Alhambra", "Prague Castle", "Hohenzollern"],
    correctIndex: 0,
    difficulty: 6,
    note: "Bavorský rozprávkový zámok Ludwiga II. — inšpirácia pre Disney. Biela veža v Alpách.",
    tags: ["obrázok", "hrad", "nemecko"],
    isImageQuestion: true,
    imageHint: "Neuschwanstein — rozprávkový zámok",
  },
  {
    id: "img-19",
    body: "Ktorý šport je na fotke?",
    answer: "Curling",
    options: ["Curling", "Bobsleigh", "Ľadový hokej", "Kroket", "Bowling", "Shuffleboard"],
    correctIndex: 0,
    difficulty: 7,
    note: "Kameň na ľade, metly, ľadová dráha — zimné olympijské, väčšina pub tímov netuší.",
    tags: ["obrázok", "šport", "zima"],
    isImageQuestion: true,
    imageHint: "Curling — kameň a metly",
  },
  {
    id: "img-20",
    body: "Ktorá eurobankovka je na fotke?",
    answer: "50 €",
    options: ["5 €", "10 €", "20 €", "50 €", "100 €", "200 €"],
    correctIndex: 3,
    difficulty: 5,
    note: "Oranžovo-hnedá 50 € s mostom renesancie. Detail architektúry alebo celá bankovka.",
    tags: ["obrázok", "ekonomika", "európa"],
    isImageQuestion: true,
    imageHint: "50 € bankovka",
  },
];
