import type { QuizBankQuestion } from "@/lib/quiz-question-bank";

/** Ďalších 50 pub otázok (bank-62 – bank-111) — overené fakty, obtiažnosť 5–9. */
export const PUB_QUIZ_BANK_EXTRA_2: QuizBankQuestion[] = [
  {
    id: "bank-62",
    body: "Ktorá krajina má na svete najviac ostrovov?",
    answer: "Švédsko",
    options: ["Fínsko", "Indonézia", "Nórsko", "Švédsko", "Filipíny", "Kanada"],
    correctIndex: 3,
    difficulty: 8,
    note: "Fínsko je obľúbená pasca (tisíce jazier a ostrovov), ale Švédsko má viac než 220 000 ostrovov. Indonézia je najväčší archipel, nie najpočetnejší.",
    tags: ["geografia", "švédsko"],
  },
  {
    id: "bank-63",
    body: "Ktorý český panovník bol posledným mužským predstaviteľom rodu Přemyslovcov na tróne?",
    answer: "Václav III.",
    options: ["Václav II.", "Václav III.", "Jan Lucemburský", "Karel IV.", "Václav I.", "Přemysl Otakar II."],
    correctIndex: 1,
    difficulty: 8,
    note: "Karel IV. je slávnejší, ale dynastia skončila vraždou Václava III. v Olomouci (1306). Jan už bol Lucemburský.",
    tags: ["história", "česko"],
  },
  {
    id: "bank-64",
    body: "V ktorej krajine sa natáčala väčšina exteriérov Stredozeme vo filme Pán prsteňov (trilógia)?",
    answer: "Nový Zéland",
    options: ["Nový Zéland", "Írsko", "Island", "Škótsko", "Nórsko", "Kanada"],
    correctIndex: 0,
    difficulty: 6,
    note: "Írsko a Škótsko lákajú kvôli keltskej atmosfére, ale Peter Jackson točil hlavne na Novom Zélande — od Hobitína po Tongariro.",
    tags: ["film", "nový zéland"],
  },
  {
    id: "bank-65",
    body: "Ktorý hokejista vyhral ako hráč najviac Stanley Cupov v histórii NHL?",
    answer: "Henri Richard",
    options: ["Wayne Gretzky", "Henri Richard", "Mario Lemieux", "Jean Béliveau", "Maurice Richard", "Mark Messier"],
    correctIndex: 1,
    difficulty: 9,
    note: "Gretzky je ikona, ale „Pocket Rocket“ Henri Richard má 11 prsteňov. Maurice Richard (brat) má 8 — ďalšia častá pasca v pub kvíze.",
    tags: ["šport", "hokej"],
  },
  {
    id: "bank-66",
    body: "Ktorý chemický prvok má najvyššiu teplotu tavenia zo všetkých prvkov?",
    answer: "Volfrám (wolfram)",
    options: ["Uhlík", "Osmium", "Volfrám (wolfram)", "Titán", "Rénium", "Platina"],
    correctIndex: 2,
    difficulty: 8,
    note: "Uhlík v grafeite vyzerá „najtvrdší“, ale pri bežnom tlaku má vysokú teplotu sublimácie. Volfrám taví pri cca 3422 °C — pub klasika.",
    tags: ["chémia", "prvky"],
  },
  {
    id: "bank-67",
    body: "Ktorý slovenský básnik je autorom básne Mor ho!?",
    answer: "Pavol Országh Hviezdoslav",
    options: [
      "Pavol Országh Hviezdoslav",
      "Andrej Sládkovič",
      "Ján Hollý",
      "Samo Chalupka",
      "Janko Kráľ",
      "Pavol Országh-Veselý",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "Sládkovič = Marína, Hollý = Svätopluk. Hviezdoslavova Mor ho! je povinná školská, v pube ju ale mýlia s romantikmi.",
    tags: ["literatúra", "slovensko"],
  },
  {
    id: "bank-68",
    body: "Ktoré mesto je druhé najľudnatejšie na Slovensku (po Bratislave)?",
    answer: "Košice",
    options: ["Košice", "Prešov", "Žilina", "Nitra", "Banská Bystrica", "Trnava"],
    correctIndex: 0,
    difficulty: 6,
    note: "Prešov je tretí, Žilina štvrtý. Košice sú dlhodobo druhé — pasca je tipovať „východ“ bez poradia.",
    tags: ["geografia", "slovensko"],
  },
  {
    id: "bank-69",
    body: "Ktorý český film získal Oscara za najlepší medzinárodný film (1996)?",
    answer: "Kolja",
    options: ["Kolja", "Obecná škola", "Pelíšky", "Musíme si pomáhať", "Hoří, má panenko", "Closely Watched Trains"],
    correctIndex: 0,
    difficulty: 8,
    note: "Musíme si pomáhať vyhralo neskôr (1997). Kolja Jana Svěráka je pub pasca — mnohí tipujú Hrabalovu Ostře sledované vlaky.",
    tags: ["film", "česko"],
  },
  {
    id: "bank-70",
    body: "Ktorá Beethovenova symfónia obsahuje Ódu na radosť?",
    answer: "9. symfónia",
    options: ["5. symfónia", "6. symfónia", "7. symfónia", "8. symfónia", "9. symfónia", "3. symfónia"],
    correctIndex: 4,
    difficulty: 5,
    note: "Piatá má slávny úvod „ta-ta-ta-tá“, ale finálny chór je až v deviatej. V pube sa to mieša s Eroicom (3.).",
    tags: ["hudba", "beethoven"],
  },
  {
    id: "bank-71",
    body: "Z ktorej krajiny pochádza tradičné syrové jedlo fondue?",
    answer: "Švajčiarsko",
    options: ["Švajčiarsko", "Francúzsko", "Rakúsko", "Taliansko", "Nemecko", "Holandsko"],
    correctIndex: 0,
    difficulty: 6,
    note: "Francúzsko má Savojsko hneď vedľa, takže polovica stolov tipuje Alpy vo všeobecnosti. Klasika je švajčiarska.",
    tags: ["jedlo", "švajčiarsko"],
  },
  {
    id: "bank-72",
    body: "Kto je považovaný za vynálezcu World Wide Web (HTTP, URL, HTML)?",
    answer: "Tim Berners-Lee",
    options: ["Tim Berners-Lee", "Bill Gates", "Steve Jobs", "Larry Page", "Vint Cerf", "Al Gore"],
    correctIndex: 0,
    difficulty: 6,
    note: "Al Gore je internetový vtip, Google = Page/Brin, Jobs = Apple. Berners-Lee navrhol web v CERNe v roku 1989.",
    tags: ["technológia", "internet"],
  },
  {
    id: "bank-73",
    body: "Ktorý americký prezident odstúpil po škandále Watergate?",
    answer: "Richard Nixon",
    options: ["Richard Nixon", "Lyndon B. Johnson", "Gerald Ford", "Jimmy Carter", "Ronald Reagan", "John F. Kennedy"],
    correctIndex: 0,
    difficulty: 6,
    note: "Ford Nixonov nástupca — tímy ho tipujú, lebo „prebral úrad“. Odstúpil ale Nixon v auguste 1974.",
    tags: ["politika", "usa"],
  },
  {
    id: "bank-74",
    body: "Koľko žalúdkov má typická dospelá krava?",
    answer: "Štyri",
    options: ["Jeden", "Dva", "Tri", "Štyri", "Päť", "Šesť"],
    correctIndex: 3,
    difficulty: 7,
    note: "Prežúvavce majú štyri oddely (vrecúško, čepeľ, kniha, slez). Jedno žalúdok je ľudská pasca.",
    tags: ["zvieratá", "hospodárstvo"],
  },
  {
    id: "bank-75",
    body: "Ktorá stavba bola najvyššou na svete tesne pred dokončením Eiffelovej veže (1889)?",
    answer: "Washingtonský monument",
    options: [
      "Kolínska katedrála",
      "Washingtonský monument",
      "Pyramída v Gíze",
      "Big Ben",
      "Pisa veža",
      "Empire State Building",
    ],
    correctIndex: 1,
    difficulty: 9,
    note: "Kolínska katedrála bola najvyššia len do roku 1884. Potom Washingtonský monument (~169 m), kým Eiffel neprekonal obe.",
    tags: ["architektúra", "usa"],
  },
  {
    id: "bank-76",
    body: "Ktorá rieka preteká centrom Prahy?",
    answer: "Vltava",
    options: ["Vltava", "Labe", "Morava", "Ohře", "Berounka", "Sázava"],
    correctIndex: 0,
    difficulty: 5,
    note: "Labe je väčší tok v Česku, ale cez Prahu ide Vltava. Labe vzniká až pri Mělníku spojením Vltavy a Labe z hor.",
    tags: ["geografia", "česko"],
  },
  {
    id: "bank-77",
    body: "V ktorom roku vypukla prvá svetová vojna?",
    answer: "1914",
    options: ["1912", "1914", "1916", "1918", "1939", "1905"],
    correctIndex: 1,
    difficulty: 5,
    note: "1918 je koniec vojny — najčastejšia pasca. Sarajevský atentát bol 28. júna 1914.",
    tags: ["história", "prvá svetová"],
  },
  {
    id: "bank-78",
    body: "Ktorý diel trilógie Pán prsteňov získal na jednej Oscarovej ceremónii 11 ocenení (2004)?",
    answer: "Pán prsteňov: Návrat kráľa",
    options: [
      "Pán prsteňov: Spoločenstvo Prsteňa",
      "Pán prsteňov: Dve veže",
      "Pán prsteňov: Návrat kráľa",
      "Hobit: Neočakávaná cesta",
      "Titanic",
      "Ben-Hur",
    ],
    correctIndex: 2,
    difficulty: 7,
    note: "Titanic a Ben-Hur majú tiež 11 Oscarov celkovo, ale tu ide o jediný film trilógie, čo vyčistil stôl. Prvé dva diely mali menej.",
    tags: ["film", "oscar"],
  },
  {
    id: "bank-79",
    body: "Ktorá krajina vyhrala majstrovstvá sveta vo futbale 2018?",
    answer: "Francúzsko",
    options: ["Francúzsko", "Chorvátsko", "Brazília", "Nemecko", "Argentína", "Španielsko"],
    correctIndex: 0,
    difficulty: 5,
    note: "Chorvátsko bolo vo finále, Argentína vyhrala až 2022. Francúzsko 4:2 v Moskve.",
    tags: ["šport", "futbal"],
  },
  {
    id: "bank-80",
    body: "Aký je chemický symbol striebra?",
    answer: "Ag",
    options: ["Ag", "Au", "Si", "Sr", "Ar", "Sb"],
    correctIndex: 0,
    difficulty: 6,
    note: "Au = zlato (aurum), Si = silícium. Ag z latinského argentum — znie to ako „Argón“, pub pasca.",
    tags: ["chémia", "striebro"],
  },
  {
    id: "bank-81",
    body: "Ktorý slovenský hokejista vyhral Stanley Cup ako prvý zo slovenských hráčov?",
    answer: "Peter Bondra",
    options: ["Peter Bondra", "Miroslav Šatan", "Marián Hossa", "Peter Šťastný", "Marián Gáborík", "Zdeno Chára"],
    correctIndex: 0,
    difficulty: 9,
    note: "Šťastný je legenda, ale Stanley Cup nevyhral. Bondra s Washingtonom 1998 — Hossa a Gáborík prišli neskôr.",
    tags: ["šport", "slovensko"],
  },
  {
    id: "bank-82",
    body: "Ktorý český spisovateľ napísal novelu Ostře sledované vlaky?",
    answer: "Bohumil Hrabal",
    options: [
      "Bohumil Hrabal",
      "Milan Kundera",
      "Jaroslav Hašek",
      "Franz Kafka",
      "Karel Čapek",
      "Ladislav Fuks",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "Hašek = Osudy dobrého vojáka Švejka, Kundera = Nesnesiteľná ľahkosť bytia. Hrabal je pub pasca medzi nimi.",
    tags: ["literatúra", "česko"],
  },
  {
    id: "bank-83",
    body: "Ktorá krajina je považovaná za kolísku moderného póla?",
    answer: "Argentína",
    options: ["Argentína", "Spojené štáty", "Spojené kráľovstvo", "India", "Austrália", "Uruguaj"],
    correctIndex: 0,
    difficulty: 8,
    note: "Britskí dôstojníci hru rozšírili, ale formalizovali ju v Argentíne (Buenos Aires) koncom 19. storočia.",
    tags: ["šport", "argentína"],
  },
  {
    id: "bank-84",
    body: "Aký destilát je základom klasického mojita?",
    answer: "Biely rum",
    options: ["Biely rum", "Vodka", "Gin", "Tequila", "Cognac", "Whisky"],
    correctIndex: 0,
    difficulty: 6,
    note: "Vodka collins a gin tonic sú silné konkurenti v tipovaní. Klasika: rum, mäta, limetka, cukor, soda.",
    tags: ["jedlo", "kocktaily"],
  },
  {
    id: "bank-85",
    body: "Kto získal v USA patent na telefón v roku 1876?",
    answer: "Alexander Graham Bell",
    options: [
      "Alexander Graham Bell",
      "Thomas Edison",
      "Nikola Tesla",
      "Guglielmo Marconi",
      "Samuel Morse",
      "Antonio Meucci",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "Edison = žiarovka, Tesla = AC. Meucci mal skorší prototyp, ale patent a pub odpoveď je Bell.",
    tags: ["technológia", "vynálezy"],
  },
  {
    id: "bank-86",
    body: "Ktorá politická strana vyhrala parlamentné voľby na Slovensku v roku 2010?",
    answer: "Smer – sociálna demokracia",
    options: [
      "Smer – sociálna demokracia",
      "SDKÚ-DS",
      "SaS",
      "KDH",
      "SMK",
      "Most–Híd",
    ],
    correctIndex: 0,
    difficulty: 8,
    note: "Smer vyhral, ale vládu potom zostavila pravicová koalícia (Radičová). Tímy tipujú víťaza koalície, nie volieb.",
    tags: ["politika", "slovensko"],
  },
  {
    id: "bank-87",
    body: "Ktoré cicavce trávi spánkom najviac hodín za deň (typicky až 22)?",
    answer: "Koala",
    options: ["Koala", "Leňochod", "Netopier", "Mačka", "Medveď", "Delfín"],
    correctIndex: 0,
    difficulty: 7,
    note: "Leňochod je pomalý, nie najspiacejší. Niektoré netopiere majú podobné čísla, ale koala je pub štandard.",
    tags: ["zvieratá", "austrália"],
  },
  {
    id: "bank-88",
    body: "Ktorá katedrála je najväčšou gotickou katedrálou sveta podľa objemu?",
    answer: "Katedrála sv. Márie v Seville",
    options: [
      "Katedrála sv. Márie v Seville",
      "Kolínska katedrála",
      "Notre-Dame v Paríži",
      "Katedrála v Miláne",
      "Westminster Abbey",
      "Katedrála sv. Víta v Prahe",
    ],
    correctIndex: 0,
    difficulty: 9,
    note: "Kolínsko je najvyššie veže, Miláno je obrovské — ale objemovo vedie Sevilla. Notre-Dame je stredne veľká.",
    tags: ["architektúra", "španielsko"],
  },
  {
    id: "bank-89",
    body: "Ktoré mesto je oficiálnym hlavným mestom Austrálie?",
    answer: "Canberra",
    options: ["Canberra", "Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
    correctIndex: 0,
    difficulty: 6,
    note: "Sydney má Operu, Melbourne bolo dočasné hlavné mesto — Canbera bola založená ako kompromis.",
    tags: ["geografia", "austrália"],
  },
  {
    id: "bank-90",
    body: "Ktorý egyptský faraón nechal postaviť najväčšiu pyramídu v Gíze?",
    answer: "Cheops (Chufu)",
    options: ["Cheops (Chufu)", "Chefren", "Mykerín", "Tutanchamón", "Ramses II.", "Akhenaten"],
    correctIndex: 0,
    difficulty: 6,
    note: "Chefrenova pyramída vyzerá vyššie (väčší sokol), ale Veľká pyramída je Cheopsova. Tutanchamón je slávny, nie staviteľ.",
    tags: ["história", "egypt"],
  },
  {
    id: "bank-91",
    body: "Ktorý herec získal posmrtného Oscara za Jokera vo filme Temný rytier (2008)?",
    answer: "Heath Ledger",
    options: ["Heath Ledger", "Joaquin Phoenix", "Jack Nicholson", "Jared Leto", "Christian Bale", "Tom Hardy"],
    correctIndex: 0,
    difficulty: 6,
    note: "Phoenix vyhral za Jokera 2020, Nicholson hral staršie verzie. Ledger = Nolan, pub pasca medzi Jokerami.",
    tags: ["film", "oscar"],
  },
  {
    id: "bank-92",
    body: "Koľko etáp (dní jazdy) má tradične Tour de France?",
    answer: "21",
    options: ["15", "18", "20", "21", "23", "25"],
    correctIndex: 3,
    difficulty: 7,
    note: "Tri týždne ≈ 21 dní jazdy + 2 dni voľna. Tip 20 alebo 23 je klasika.",
    tags: ["šport", "cyklistika"],
  },
  {
    id: "bank-93",
    body: "Aký je chemický symbol železa?",
    answer: "Fe",
    options: ["Fe", "Zn", "Fr", "F", "Ir", "Fl"],
    correctIndex: 0,
    difficulty: 5,
    note: "Latinské ferrum. Zn = zinek, F = fluor — zvuková pasca pre netrpezlivých.",
    tags: ["chémia", "železo"],
  },
  {
    id: "bank-94",
    body: "Ktorý režisér natočil slovenský film Jánošík (2009)?",
    answer: "Agnieszka Holland",
    options: [
      "Agnieszka Holland",
      "Juraj Jakubisko",
      "Martin Šulík",
      "Jan Svěrák",
      "Pavel Jechouček",
      "Peter Bebjak",
    ],
    correctIndex: 0,
    difficulty: 9,
    note: "Jakubisko mal staršie Jánošíky, ale verzia 2009 je poľsko-česko-slovenská s Holland. V pube tipujú domácich.",
    tags: ["film", "slovensko"],
  },
  {
    id: "bank-95",
    body: "Ktorý český skladateľ je autorom symfónie známej ako Nový svet (Vlčia dráha)?",
    answer: "Antonín Dvořák",
    options: [
      "Antonín Dvořák",
      "Bedřich Smetana",
      "Leoš Janáček",
      "Gustav Mahler",
      "Bohuslav Martinů",
      "Josef Suk",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "Smetana = Vltava z Má vlasti. Dvořák skomponoval Nový svet v Amerike — najhranejšia pub pasca medzi Čechmi.",
    tags: ["hudba", "česko"],
  },
  {
    id: "bank-96",
    body: "V ktorom meste vznikol pôvodný ležiak typu Pilsner Urquell (1842)?",
    answer: "Plzeň",
    options: ["Plzeň", "Praha", "Brno", "České Budějovice", "Pardubice", "Ostrava"],
    correctIndex: 0,
    difficulty: 6,
    note: "Budějovice majú Budvar, ale Pilsner = Plzeň (nemecky Pilsen). Praha tipuje polovica stola.",
    tags: ["jedlo", "pivo"],
  },
  {
    id: "bank-97",
    body: "Ktorá spoločnosť predstavila prvý iPhone v roku 2007?",
    answer: "Apple",
    options: ["Apple", "Microsoft", "Google", "Samsung", "Nokia", "Sony"],
    correctIndex: 0,
    difficulty: 5,
    note: "Samsung dominuje dnes, Nokia vládla predtým — ale keynote 2007 bol Steve Jobs, Apple.",
    tags: ["technológia", "apple"],
  },
  {
    id: "bank-98",
    body: "Kto bol prvým prezidentom samostatnej Českej republiky (od 1993)?",
    answer: "Václav Havel",
    options: ["Václav Havel", "Václav Klaus", "Miloš Zeman", "Alexander Dubček", "Gustáv Husák", "Tomáš Garrigue Masaryk"],
    correctIndex: 0,
    difficulty: 6,
    note: "Klaus bol druhý prezident, Masaryk prvá republika. Havel symbolizuje samostatné Česko.",
    tags: ["politika", "česko"],
  },
  {
    id: "bank-99",
    body: "Ktoré zviera je dlhodobo symbolom nadácie WWF (World Wide Fund for Nature)?",
    answer: "Panda veľká",
    options: ["Panda veľká", "Tiger", "Lev", "Modrá veľryba", "Gorila", "Orangutan"],
    correctIndex: 0,
    difficulty: 5,
    note: "Tiger a lev sú silné alternatívy, ale čierno-biela panda je logo od 1961.",
    tags: ["zvieratá", "panda"],
  },
  {
    id: "bank-100",
    body: "Ako sa volá najstarší most cez Dunaj spájajúci budynskú a peštiansku stranu Budapešti (1849)?",
    answer: "Reťazový most (Széchenyi lánchíd)",
    options: [
      "Reťazový most (Széchenyi lánchíd)",
      "Most Margit",
      "Most Elisabeth",
      "Most Liberty",
      "Most Arpad",
      "Most Petőfi",
    ],
    correctIndex: 0,
    difficulty: 8,
    note: "Margit je ostrovný most, ostatné sú mladšie. Ikonický „Chain Bridge“ pri nočnom Budapešti.",
    tags: ["architektúra", "maďarsko"],
  },
  {
    id: "bank-101",
    body: "Ktorá planéta je najbližšie k Slnku?",
    answer: "Merkúr",
    options: ["Merkúr", "Venuša", "Mars", "Zem", "Jupiter", "Saturn"],
    correctIndex: 0,
    difficulty: 5,
    note: "Venuša je najbližšia k Zemi, nie k Slnku — najčastejšia astronomická pasca v pube.",
    tags: ["astronómia", "planéty"],
  },
  {
    id: "bank-102",
    body: "V ktorom roku vypukla Veľká francúzska revolúcia (dobytie Bastily)?",
    answer: "1789",
    options: ["1776", "1789", "1792", "1804", "1815", "1848"],
    correctIndex: 1,
    difficulty: 6,
    note: "1776 = USA, 1804 = Napoleon cisár. Bastila padla 14. júla 1789.",
    tags: ["história", "francúzsko"],
  },
  {
    id: "bank-103",
    body: "Ktorý tenisista vyhral mužský singel na Wimbledone najviackrát v Open ére?",
    answer: "Roger Federer",
    options: ["Roger Federer", "Novak Djoković", "Rafael Nadal", "Pete Sampras", "Björn Borg", "Andy Murray"],
    correctIndex: 0,
    difficulty: 7,
    note: "Djoković dobehol na 7, Federer má 8 wimbledonských titulov. Nadal = antuka, nie tráva.",
    tags: ["šport", "tenis"],
  },
  {
    id: "bank-104",
    body: "Ktorý plyn v zemskej atmosfére primárne produkuje zelenú farbu polárnej žiary (aurory)?",
    answer: "Kyslík",
    options: ["Kyslík", "Dusík", "Argon", "Vodík", "Hélium", "CO₂"],
    correctIndex: 0,
    difficulty: 9,
    note: "Dusík dáva často červenú/modrú. Zelená (~557 nm) je typická pre excitovaný kyslík vo výške 100–300 km.",
    tags: ["fyzika", "aurora"],
  },
  {
    id: "bank-105",
    body: "Ktoré slovenské mesto je zapísané na UNESCO predovšetkým vďaka baníckemu dedičstvu striebra?",
    answer: "Banská Štiavnica",
    options: [
      "Banská Štiavnica",
      "Kremnica",
      "Banská Bystrica",
      "Rožňava",
      "Spišská Nová Ves",
      "Revúca",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "Kremnica má mincovňu (zlato), Bystrica názov „Banská“, ale UNESCO banícky komplex = Štiavnica.",
    tags: ["geografia", "slovensko"],
  },
  {
    id: "bank-106",
    body: "Ktorý český hokejista dosiahol ako druhý hráč v histórii NHL hranicu 700 gólov?",
    answer: "Jaromír Jágr",
    options: [
      "Jaromír Jágr",
      "Wayne Gretzky",
      "Mario Lemieux",
      "Dominik Hašek",
      "Peter Šťastný",
      "Milan Hejduk",
    ],
    correctIndex: 0,
    difficulty: 8,
    note: "Gretzky bol prvý na 700+. Jágr druhý — pub otázka pre starších fanúšikov, mladší tipujú Hašeka (brankár).",
    tags: ["šport", "česko"],
  },
  {
    id: "bank-107",
    body: "Ktorá britská kapela vydala skladbu Bohemian Rhapsody?",
    answer: "Queen",
    options: ["Queen", "The Beatles", "Led Zeppelin", "Pink Floyd", "The Rolling Stones", "Deep Purple"],
    correctIndex: 0,
    difficulty: 5,
    note: "Beatles majú Hey Jude, Floyd Wish You Were Here. Bohemian Rhapsody = Mercury, Queen 1975.",
    tags: ["hudba", "queen"],
  },
  {
    id: "bank-108",
    body: "Z ktorej krajiny pochádza koreninové jedlo kimchi?",
    answer: "Kórea",
    options: ["Kórea", "Japonsko", "Čína", "Thajsko", "Vietnam", "Indonézia"],
    correctIndex: 0,
    difficulty: 5,
    note: "Japonsko = miso, Čína = Pekingská kačka. Kimchi je ikona Kórey — často tipujú Japonsko.",
    tags: ["jedlo", "kórea"],
  },
  {
    id: "bank-109",
    body: "Kto bol dlhoročným CEO automobilky Tesla pri masívnom raste značky (2008–)?",
    answer: "Elon Musk",
    options: ["Elon Musk", "Jeff Bezos", "Tim Cook", "Bill Gates", "Mark Zuckerberg", "Sundar Pichai"],
    correctIndex: 0,
    difficulty: 5,
    note: "Bezos = Amazon, Cook = Apple. Musk prevzal vedenie Tesly a stal sa tvárou značky.",
    tags: ["technológia", "tesla"],
  },
  {
    id: "bank-110",
    body: "Ktoré zviera dokáže za beh na krátku vzdialenosť prekonať rýchlosť 100 km/h?",
    answer: "Gepard",
    options: ["Gepard", "Lev", "Antilopa pružná", "Kôň", "Srnec", "Vlk"],
    correctIndex: 0,
    difficulty: 5,
    note: "Antilopa je rýchla, ale gepard ~100–120 km/h v šprinte. Lev je silnejší, nie rýchlejší.",
    tags: ["zvieratá", "safari"],
  },
  {
    id: "bank-111",
    body: "Ktorá budova bola po dokončení v roku 1931 najvyššou na svete až do roku 1970?",
    answer: "Empire State Building",
    options: [
      "Empire State Building",
      "Chrysler Building",
      "Eiffelova veža",
      "Willis Tower (Sears Tower)",
      "Petronas Towers",
      "Burj Khalifa",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "Chrysler bol krátko pred ním (1930), ale Empire State držal rekord 40 rokov. Willis Tower prekonal až 1973.",
    tags: ["architektúra", "new york"],
  },
];
