import type { QuizBankQuestion } from "@/lib/quiz-question-bank";

/** Ďalších 50 pub otázok — overené fakty, obtiažnosť cca 6–9. */
export const PUB_QUIZ_BANK_EXTRA: QuizBankQuestion[] = [
  {
    id: "bank-12",
    body: "Ktorá krajina je dlhodobo najväčším producentom kávy na svete (v zelených zrnách)?",
    answer: "Brazília",
    options: ["Brazília", "Kolumbia", "Etiópia", "Vietnam", "Indonézia", "Honduras"],
    correctIndex: 0,
    difficulty: 6,
    note: "Kolumbia je marketingová ikona, ale Brazília desaťročia vedie objem. Vietnam je silný v robuste, nie v celkovom mýte.",
    tags: ["geografia", "svet", "jedlo"],
  },
  {
    id: "bank-13",
    body: "Koľko sŕdc má typická dážďovka?",
    answer: "Päť",
    options: ["Jedno", "Dve", "Tri", "Päť", "Sedem", "Žiadne"],
    correctIndex: 3,
    difficulty: 7,
    note: "Päť párov „srdiečok“ — pub klasika, väčšina tipuje jedno alebo žiadne. Chobotnica má tri, dážďovka päť.",
    tags: ["veda", "príroda", "zvieratá"],
  },
  {
    id: "bank-14",
    body: "Ktorá rieka je najdlhšia v Európe?",
    answer: "Volga",
    options: ["Volga", "Dunaj", "Dneper", "Rýn", "Loira", "Elbe"],
    correctIndex: 0,
    difficulty: 7,
    note: "Dunaj je ikona strednej Európy, ale Volga v Rusku je dlhšia. Dunaj preteká viacerými krajinami — to je iná otázka.",
    tags: ["geografia", "európa", "svet"],
  },
  {
    id: "bank-15",
    body: "Ktorý plyn tvorí najväčší podiel zemskej atmosféry?",
    answer: "Dusík",
    options: ["Kyslík", "Dusík", "Argon", "Oxid uhličitý", "Vodík", "Hélium"],
    correctIndex: 1,
    difficulty: 6,
    note: "Kyslík ~21 %, dusík ~78 %. Tímy často tipujú kyslík, lebo „dýchame ho“.",
    tags: ["veda", "fyzika", "svet"],
  },
  {
    id: "bank-16",
    body: "V ktorej krajine vznikol croissant podľa najrozšírenejšej kulinárskej legendy (cukrárske dielo pre Osmanské obliehanie)?",
    answer: "Rakúsko",
    options: ["Rakúsko", "Francúzsko", "Taliansko", "Turecko", "Maďarsko", "Nemecko"],
    correctIndex: 0,
    difficulty: 7,
    note: "Francúzsko ho zpopularizovalo, ale legenda siedmi rokov Viedne je pub pasca. Francúzsko je falošný tip č. 1.",
    tags: ["história", "jedlo", "európa"],
  },
  {
    id: "bank-17",
    body: "Ktorá planéta Slnečnej sústavy má v súčasnosti najviac potvrdených mesiacov?",
    answer: "Saturn",
    options: ["Saturn", "Jupiter", "Urán", "Neptún", "Mars", "Zem"],
    correctIndex: 0,
    difficulty: 8,
    note: "Od objavov okolo Saturnu (2020+) prekonal Jupiter. Staré kvízy stále tipujú Jupiter — aktualizovaná pub otázka.",
    tags: ["veda", "vesmír", "astronómia"],
  },
  {
    id: "bank-18",
    body: "Aký je chemický symbol olova?",
    answer: "Pb",
    options: ["Pb", "Pl", "Ol", "Po", "Ld", "Le"],
    correctIndex: 0,
    difficulty: 6,
    note: "Plumbum — latinský názov. Po je polónium, tímy zamieňajú podľa zvuku.",
    tags: ["veda", "chémia", "svet"],
  },
  {
    id: "bank-19",
    body: "Ktorý štát USA bol prijatý do Únie ako posledný?",
    answer: "Havaj",
    options: ["Havaj", "Aljaška", "Arizona", "New Mexico", "Alabama", "Texas"],
    correctIndex: 0,
    difficulty: 7,
    note: "Aljaška 1959 ako 49., Havaj ešte v tom roku ako 50. Aljaška je obľúbená pasca.",
    tags: ["geografia", "usa", "história"],
  },
  {
    id: "bank-20",
    body: "Ktorý alkohol je základom klasického Negroni?",
    answer: "Gin",
    options: ["Gin", "Vodka", "Rum", "Whisky", "Tequila", "Brandy"],
    correctIndex: 0,
    difficulty: 7,
    note: "Gin, Campari, červený vermut. Vodka Negroni existuje, ale klasika je gin.",
    tags: ["jedlo", "kultúra", "svet"],
  },
  {
    id: "bank-21",
    body: "Ktorý vnútorný orgán u dospelého človeka dokáže obnoviť väčšinu svojej hmotnosti po poškodení?",
    answer: "Pečeň",
    options: ["Pečeň", "Oblička", "Srdce", "Pľúca", "Slezina", "Žalúdok"],
    correctIndex: 0,
    difficulty: 6,
    note: "Regenerácia pečene je unikátna — srdce a mozog sa neobnovia takto. Oblička áno čiastočne, ale pub odpoveď je pečeň.",
    tags: ["veda", "medicína", "svet"],
  },
  {
    id: "bank-22",
    body: "V ktorej krajine leží historické mesto Timbuktu?",
    answer: "Mali",
    options: ["Mali", "Niger", "Senegal", "Burkina Faso", "Mauretánia", "Čad"],
    correctIndex: 0,
    difficulty: 7,
    note: "Synonymum „koniec sveta“ — Mali v Sahare. Niger je sused, nie domov Timbuktu.",
    tags: ["geografia", "afrika", "história"],
  },
  {
    id: "bank-23",
    body: "Ktorý spisovateľ napísal román Sto rokov samoty?",
    answer: "Gabriel García Márquez",
    options: [
      "Gabriel García Márquez",
      "Jorge Luis Borges",
      "Pablo Neruda",
      "Isabel Allende",
      "Mario Vargas Llosa",
      "Julio Cortázar",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "Magický realizmus, Kolumbia. Borges je pasca pre latinoamerickú literatúru.",
    tags: ["literatúra", "kultúra", "svet"],
  },
  {
    id: "bank-24",
    body: "Ktorý kov je kvapalný pri bežnej izbovej teplote?",
    answer: "Rtuť",
    options: ["Rtuť", "Galium", "Césium", "Olovo", "Striebro", "Hliník"],
    correctIndex: 0,
    difficulty: 6,
    note: "Galium sa topí v dlani, ale izbová teplota = rtuť. Césium reaguje so vzduchom — nie stabilná kvapalina.",
    tags: ["veda", "chémia", "svet"],
  },
  {
    id: "bank-25",
    body: "Ktorá krajina má na erbe lev a jednorožca (štátny erb)?",
    answer: "Spojené kráľovstvo",
    options: [
      "Spojené kráľovstvo",
      "Škótsko",
      "Dánsko",
      "Nórsko",
      "Monako",
      "Luxembursko",
    ],
    correctIndex: 0,
    difficulty: 6,
    note: "Lev (Anglicko) a jednorožec (Škótsko) — oficiálny erb UK. Škótsko samostatne má len jednorožca.",
    tags: ["história", "európa", "kultúra"],
  },
  {
    id: "bank-26",
    body: "V ktorom roku bola založená NATO?",
    answer: "1949",
    options: ["1945", "1947", "1949", "1952", "1955", "1939"],
    correctIndex: 2,
    difficulty: 7,
    note: "Washingtonská zmluva apríl 1949. 1945 je koniec vojny — pasca.",
    tags: ["história", "politika", "svet"],
  },
  {
    id: "bank-27",
    body: "Ktorý vták dosahuje pri kľukovitom letu najvyššiu zaznamenanú rýchlosť (ponor)?",
    answer: "Sokol sťahovavý",
    options: [
      "Sokol sťahovavý",
      "Orol skalný",
      "Albatros",
      "Kondor",
      "Jastrab",
      "Vlastovka",
    ],
    correctIndex: 0,
    difficulty: 8,
    note: "Peregrine falcon — ponor cez 300 km/h. Albatros lieta dlho, nie najrýchlejší ponor.",
    tags: ["príroda", "zvieratá", "veda"],
  },
  {
    id: "bank-28",
    body: "Ktorý európsky štát nemá vlastnú pravidelnú armádu (len políciu a prípadnú obranu)?",
    answer: "Andorra",
    options: ["Andorra", "Island", "Luxembursko", "Monako", "Malta", "San Maríno"],
    correctIndex: 0,
    difficulty: 8,
    note: "Andorra sa spolieha na Francúzsko/Španielsko. Island má pobrežnú stráž — nie je úplne bez ozbrojených zložiek.",
    tags: ["geografia", "európa", "politika"],
  },
  {
    id: "bank-29",
    body: "Aký je najmenší suverénny štát na svete (rozlohou)?",
    answer: "Vatikán",
    options: ["Vatikán", "Monako", "San Maríno", "Liechtenstein", "Malta", "Andorra"],
    correctIndex: 0,
    difficulty: 6,
    note: "Vatikán ~0,44 km². Monaco je druhé — tímy často tipujú Monako.",
    tags: ["geografia", "svet", "európa"],
  },
  {
    id: "bank-30",
    body: "Ktorý grécky filozof bol odsúdený na smrť vypitím extraktu z hemlocku?",
    answer: "Sokrates",
    options: ["Sokrates", "Platón", "Aristoteles", "Diogenes", "Epikúros", "Pythagoras"],
    correctIndex: 0,
    difficulty: 6,
    note: "399 pred n. l., Athény. Platón bol žiak, nie obeť.",
    tags: ["história", "filozofia", "svet"],
  },
  {
    id: "bank-31",
    body: "Ktorý kov sa tradične používa pri galvanickom zinkovaní železa proti korózii?",
    answer: "Zinok",
    options: ["Zinok", "Nikel", "Chróm", "Meď", "Cín", "Hliník"],
    correctIndex: 0,
    difficulty: 7,
    note: "Zinc coating — poznáme z „pozinkovaného“ plechu. Nikel je iný proces.",
    tags: ["veda", "chémia", "technológie"],
  },
  {
    id: "bank-32",
    body: "V ktorej krajine vznikla značka IKEA?",
    answer: "Švédsko",
    options: ["Švédsko", "Dánsko", "Nórsko", "Fínsko", "Nemecko", "Holandsko"],
    correctIndex: 0,
    difficulty: 5,
    note: "Ingvar Kamprad, Älmhult. Nemecko je najväčší trh, nie pôvod.",
    tags: ["kultúra", "história", "európa"],
  },
  {
    id: "bank-33",
    body: "Ktorá krajina má najviac susedných štátov (z celkového počtu)?",
    answer: "Rusko a Čína (zhodne 14)",
    options: [
      "Rusko a Čína (zhodne 14)",
      "Brazília",
      "Nemecko",
      "Poľsko",
      "Francúzsko",
      "India",
    ],
    correctIndex: 0,
    difficulty: 9,
    note: "Rusko aj Čína majú 14 susedov — remíza. Brazília 10, Nemecko 9. Ťažká, ale férová otázka.",
    tags: ["geografia", "svet", "politika"],
  },
  {
    id: "bank-34",
    body: "Ktorý chemický prvok reaguje explozívne s vodou (alkalický kov)?",
    answer: "Sodík",
    options: ["Sodík", "Draslík", "Vápnik", "Horčík", "Lítium", "Hliník"],
    correctIndex: 0,
    difficulty: 7,
    note: "Sodík aj draslík áno — v školskom deme klasicky sodík. Draslík ešte prudšie, ale pub štandard je sodík.",
    tags: ["veda", "chémia", "svet"],
  },
  {
    id: "bank-35",
    body: "V ktorej krajine sa nachádza historická oblasť Transylvánia?",
    answer: "Rumunsko",
    options: ["Rumunsko", "Maďarsko", "Bulharsko", "Srbsko", "Ukrajina", "Slovensko"],
    correctIndex: 0,
    difficulty: 6,
    note: "Drakula marketing — Rumunsko, nie Maďarsko (hoci história sa prelína).",
    tags: ["geografia", "európa", "história"],
  },
  {
    id: "bank-36",
    body: "Ktorý jazyk má najviac rodných hovoriacich na svete?",
    answer: "Mandarínčina",
    options: ["Mandarínčina", "Angličtina", "Španielčina", "Hindčina", "Arabčina", "Portugalčina"],
    correctIndex: 0,
    difficulty: 6,
    note: "Angličtina vedie ako druhý jazyk, nie rodný. Španielčina je tretia v rodených.",
    tags: ["kultúra", "svet", "geografia"],
  },
  {
    id: "bank-37",
    body: "Ktorý oceán je najmenší (plochou)?",
    answer: "Arktický",
    options: ["Arktický", "Indický", "Atlantický", "Tichý", "Južný", "Žiadny — sú rovnako veľké"],
    correctIndex: 0,
    difficulty: 6,
    note: "Arktický — okolo severného pólu. Južný okolo Antarktídy je väčší.",
    tags: ["geografia", "svet", "príroda"],
  },
  {
    id: "bank-38",
    body: "Koľko zubov má dospelý človek s úplným chrupom vrátane zubov múdrosti?",
    answer: "32",
    options: ["28", "30", "32", "34", "36", "24"],
    correctIndex: 2,
    difficulty: 6,
    note: "8 x 4 = 32. Bez múdrosti 28 — otázka špecifikuje úplný chrup.",
    tags: ["veda", "medicína", "svet"],
  },
  {
    id: "bank-39",
    body: "Ktorý autor vytvoril detektíva Hercule Poirota?",
    answer: "Agatha Christie",
    options: [
      "Agatha Christie",
      "Arthur Conan Doyle",
      "Raymond Chandler",
      "Dorothy L. Sayers",
      "Graham Greene",
      "Ruth Rendell",
    ],
    correctIndex: 0,
    difficulty: 5,
    note: "Belgičan s fúzikmi — Christie. Doyle = Holmes.",
    tags: ["literatúra", "kultúra", "svet"],
  },
  {
    id: "bank-40",
    body: "Ktorý filmový režisér režíroval Inception a Interstellar?",
    answer: "Christopher Nolan",
    options: [
      "Christopher Nolan",
      "Denis Villeneuve",
      "Ridley Scott",
      "Steven Spielberg",
      "James Cameron",
      "David Fincher",
    ],
    correctIndex: 0,
    difficulty: 6,
    note: "Nolan — sny a čas. Villeneuve Dune/Arrival — častá pasca.",
    tags: ["film", "kultúra", "svet"],
  },
  {
    id: "bank-41",
    body: "Aký je najvyšší vrch Európy mimo Kaukazu (podľa medzinárodne uznávaných hraníc)?",
    answer: "Mont Blanc",
    options: ["Mont Blanc", "Matterhorn", "Elbrus", "Grossglockner", "Zugspitze", "Rysy"],
    correctIndex: 0,
    difficulty: 8,
    note: "Elbrus je v Kaukaze (Rusko) — geologicky vyšší, ale pub verzia „Európa“ = Mont Blanc 4810 m.",
    tags: ["geografia", "európa", "príroda"],
  },
  {
    id: "bank-42",
    body: "V ktorej krajine sa hovorí portugalsky a leží mesto Rio de Janeiro?",
    answer: "Brazília",
    options: ["Brazília", "Portugalsko", "Angola", "Mozambik", "Kapverdy", "Východný Timor"],
    correctIndex: 0,
    difficulty: 5,
    note: "Rio nie je hlavné mesto (Brasília), ale je v Brazílii — Portugalsko je pasca.",
    tags: ["geografia", "svet", "kultúra"],
  },
  {
    id: "bank-43",
    body: "Ktorý prvok má v periodickom systéme symbol Au?",
    answer: "Zlato",
    options: ["Zlato", "Striebro", "Hliník", "Argón", "Osmium", "Aurín (fiktívny)"],
    correctIndex: 0,
    difficulty: 5,
    note: "Aurum — latinsky. Ag = striebro — častá zámiena pri rýchlom tipovaní.",
    tags: ["veda", "chémia", "svet"],
  },
  {
    id: "bank-44",
    body: "Ktorá krajina má na mapě tvar „boot“ ( čižmy )?",
    answer: "Taliansko",
    options: ["Taliansko", "Chorvátsko", "Grécko", "Španielsko", "Bulharsko", "Portugalsko"],
    correctIndex: 0,
    difficulty: 5,
    note: "Apeninský polostrov — základná geografia, ale funguje aj v pub kvíze ako rýchla.",
    tags: ["geografia", "európa", "svet"],
  },
  {
    id: "bank-45",
    body: "Ktorý alkohol a bitter tvoria spolu s vermutom drink americano (predchodca Negroni)?",
    answer: "Campari (s červeným vermutom)",
    options: [
      "Campari (s červeným vermutom)",
      "Aperol (s proseccoom)",
      "Angostura (s rumom)",
      "Fernet (s kolou)",
      "Chartreuse (s ginom)",
      "Cointreau (s tequilou)",
    ],
    correctIndex: 0,
    difficulty: 8,
    note: "Americano = Campari + sweet vermut + soda. Negroni nahrádza sodu ginom.",
    tags: ["jedlo", "kultúra", "svet"],
  },
  {
    id: "bank-46",
    body: "Ktorý slovenský básnik napísal báseň Moru, mať?",
    answer: "Pavol Országh Hviezdoslav",
    options: [
      "Pavol Országh Hviezdoslav",
      "Ján Hollý",
      "Andrej Sládkovič",
      "Janko Kráľ",
      "Samo Chalupka",
      "Ján Botto",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "Hviezdoslav — Moru, mať je školská klasika. Sládkovič = Marína.",
    tags: ["literatúra", "slovensko", "kultúra"],
  },
  {
    id: "bank-47",
    body: "Ktoré zviera je najväčším cicavcom na Zemi?",
    answer: "Modrá veľryba",
    options: ["Modrá veľryba", "Afričný slon", "Plejtvák obrovský", "Kosatka", "Hroch", "Žirafa"],
    correctIndex: 0,
    difficulty: 5,
    note: "Modrá veľryba aj najväčšie zviera vôbec. Plejtvák obrovský je dlhší, nie ťažší.",
    tags: ["príroda", "zvieratá", "veda"],
  },
  {
    id: "bank-48",
    body: "V ktorom roku bola založená spoločnosť Google?",
    answer: "1998",
    options: ["1996", "1998", "2000", "2004", "1994", "2001"],
    correctIndex: 1,
    difficulty: 7,
    note: "Larry Page a Sergey Brin — september 1998. 2004 je IPO.",
    tags: ["technológie", "história", "svet"],
  },
  {
    id: "bank-49",
    body: "Ktorý mesiac má v priemere najbližšiu vzdialenosť od Zeme (orbitálna mechanika)?",
    answer: "Mesiac (náš)",
    options: ["Mesiac (náš)", "Mars", "Venuša", "Merkúr", "Slnko", "Jupiter"],
    correctIndex: 0,
    difficulty: 8,
    note: "Venuša najbližšia planéta pri perigé, ale Mesiac je stále bližšie než akákoľvek planéta. Pub háčik na „planéta“ vs Mesiac.",
    tags: ["veda", "vesmír", "astronómia"],
  },
  {
    id: "bank-50",
    body: "Ktorý štát USA leží úplne mimo územia Severnej Ameriky?",
    answer: "Havaj",
    options: ["Havaj", "Aljaška", "Florida", "Kalifornia", "Texas", "Washington"],
    correctIndex: 0,
    difficulty: 6,
    note: "Aljaška je exkláva na severe kontinentu, ale stále Amerika. Havaj = Tichý oceán.",
    tags: ["geografia", "usa", "svet"],
  },
  {
    id: "bank-51",
    body: "Ktorý hudobný skladateľ bol hluchý pri premiere Deviatej symfónie?",
    answer: "Ludwig van Beethoven",
    options: [
      "Ludwig van Beethoven",
      "Johann Sebastian Bach",
      "Wolfgang Amadeus Mozart",
      "Franz Schubert",
      "Johannes Brahms",
      "Richard Wagner",
    ],
    correctIndex: 0,
    difficulty: 6,
    note: "1824 Viedeň — dirigent musel otočiť na potlesk. Beethoven nepočul.",
    tags: ["hudba", "história", "kultúra"],
  },
  {
    id: "bank-52",
    body: "Ktorá krajina má na vlajke červený javorový list?",
    answer: "Kanada",
    options: ["Kanada", "Libanon", "Slovinsko", "Nórsko", "Fínsko", "Švajčiarsko"],
    correctIndex: 0,
    difficulty: 6,
    note: "Maple leaf od 1965. Libanon má cédrový strom — častá pasca v pub kvíze.",
    tags: ["geografia", "svet", "kultúra"],
  },
  {
    id: "bank-53",
    body: "Ktorý rímsky cisár legalizoval kresťanstvo ediktom milánskym (313)?",
    answer: "Konštantín Veľký",
    options: [
      "Konštantín Veľký",
      "Augustus",
      "Nero",
      "Dioklecián",
      "Trajan",
      "Marcus Aurelius",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "Edikt tolerancie — Konštantín, nie Nero (ten kresťanov prenasledoval).",
    tags: ["história", "svet", "európa"],
  },
  {
    id: "bank-54",
    body: "Aký je hlavný zdroj sladkosti v tradičnom japonskom sake?",
    answer: "Ryža",
    options: ["Ryža", "Pšenica", "Jačmeň", "Cukrová trstina", "Slad", "Potočná voda"],
    correctIndex: 0,
    difficulty: 7,
    note: "Fermentovaná ryža + kōji. Nie slad ako pri pive — pub pasca.",
    tags: ["jedlo", "kultúra", "ázia"],
  },
  {
    id: "bank-55",
    body: "Ktorý slovenský peak je najvyšším vrchom na našom území?",
    answer: "Gerlachovský štít",
    options: [
      "Gerlachovský štít",
      "Lomnický štít",
      "Kriváň",
      "Rysy",
      "Chopok",
      "Baranec",
    ],
    correctIndex: 0,
    difficulty: 6,
    note: "2654 m n. m. Lomnica 2634 — tesne druhý. Kriváň je ikona, nie výška.",
    tags: ["geografia", "slovensko", "príroda"],
  },
  {
    id: "bank-56",
    body: "Ktorý fyzik formuloval teóriu relativity?",
    answer: "Albert Einstein",
    options: [
      "Albert Einstein",
      "Isaac Newton",
      "Niels Bohr",
      "Max Planck",
      "Stephen Hawking",
      "Galileo Galilei",
    ],
    correctIndex: 0,
    difficulty: 5,
    note: "Špeciálna 1905, všeobecná 1915. Newton = gravitácia klasicizmu.",
    tags: ["veda", "fyzika", "história"],
  },
  {
    id: "bank-57",
    body: "V ktorej krajine sa nachádza pamiatka Petra?",
    answer: "Jordánsko",
    options: ["Jordánsko", "Egypt", "Sýria", "Izrael", "Irak", "Líbya"],
    correctIndex: 0,
    difficulty: 7,
    note: "Skalné mesto Nabatejcov — Jordánsko. Egypt = pyramídy, iná pasca.",
    tags: ["geografia", "história", "svet"],
  },
  {
    id: "bank-58",
    body: "Ktorý organický kyslík je hlavnou zložkou octu (okrem vody)?",
    answer: "Kyselina octová",
    options: [
      "Kyselina octová",
      "Kyselina citrónová",
      "Kyselina mliečna",
      "Kyselina mravčia",
      "Kyselina sírová",
      "Kyselina chlorovodíková",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "CH₃COOH — 5–8 % v kuchynskom octe. Citrónová = citrusy.",
    tags: ["veda", "chémia", "jedlo"],
  },
  {
    id: "bank-59",
    body: "Ktorý tenisista vyhral najviac grandslamov v histórii mužského singla (Open éra)?",
    answer: "Novak Djoković",
    options: [
      "Novak Djoković",
      "Roger Federer",
      "Rafael Nadal",
      "Pete Sampras",
      "Björn Borg",
      "Andre Agassi",
    ],
    correctIndex: 0,
    difficulty: 7,
    note: "Stav k 2024 — Djoković prekonal 24. Nadal/Federer blízko — aktualizuj ak bude medzera.",
    tags: ["šport", "svet", "kultúra"],
  },
  {
    id: "bank-60",
    body: "Ktorý európsky štát má hlavné mesto Reykjavík?",
    answer: "Island",
    options: ["Island", "Grónsko", "Faerské ostrovy", "Nórsko", "Fínsko", "Írsko"],
    correctIndex: 0,
    difficulty: 5,
    note: "Grónsko patrí Dánsku — Reykjavík je len Island.",
    tags: ["geografia", "európa", "svet"],
  },
  {
    id: "bank-61",
    body: "Ktorý český spisovateľ napísal novelu Spalovač mrtvol?",
    answer: "Ladislav Fuks",
    options: [
      "Ladislav Fuks",
      "Milan Kundera",
      "Bohumil Hrabal",
      "Franz Kafka",
      "Jaroslav Hašek",
      "Karel Čapek",
    ],
    correctIndex: 0,
    difficulty: 8,
    note: "Fuks — groteska, Karlovy Vary. Kundera = Nesnesiteľná ľahkosť bytia.",
    tags: ["literatúra", "česko", "kultúra"],
  },
];