import type { QuizBankQuestion } from "@/lib/quiz-question-bank";

/** Ďalších 100 pub otázok (bank-112 – bank-211) — overené fakty, obtiažnosť 6–9. */
export const PUB_QUIZ_BANK_EXTRA_3: QuizBankQuestion[] = [
  {
    id: "bank-112",
    body: "Ktorý hradný komplex na Slovensku je považovaný za najrozsiahlejší v strednej Európe?",
    answer: "Spišský hrad",
    options: ["Oravský hrad", "Spišský hrad", "Trenčiansky hrad", "Devín", "Bojnice", "Bratislavský hrad"],
    correctIndex: 1,
    difficulty: 7,
    note: "Bojnice je najnavštevovanejší a Orava fotogenickejší, ale Spiš pokrýva takmer 4 hektáre — pub pasca je tipovať „najkrajší“ namiesto „najväčší“.",
    tags: ["architektúra", "slovensko"],
  },
  {
    id: "bank-113",
    body: "Ktorý slovenský lyžiar získal v sezóne 2018/19 Crystal Globe v celkovom hodnotení Svetového pohára?",
    answer: "Petra Vlhová",
    options: ["Henrieta Farkašová", "Petra Vlhová", "Veronika Velez-Zuzulová", "Jana Gantnerová", "Martina Dubovská", "Barbara Kastelein"],
    correctIndex: 1,
    difficulty: 7,
    note: "Farkašová dominuje para-alpine, Velez-Zuzulová skončila skôr. Vlhová vyhrala celkový SP 2019 — mladší tipujú Shiffrinovú.",
    tags: ["šport", "slovensko"],
  },
  {
    id: "bank-114",
    body: "V ktorom roku vyšiel prvý diel slovenskej poviedky Drak sa vracia od Dobšinského?",
    answer: "1863",
    options: ["1843", "1853", "1863", "1873", "1883", "1893"],
    correctIndex: 2,
    difficulty: 9,
    note: "Dobšinský patrí k romantikom, ale Drak sa vracia vznikol až v 60. rokoch 19. storočia. Tipuje sa často rok vydania Prostonárodných slovenských povestí (1883).",
    tags: ["literatúra", "slovensko"],
  },
  {
    id: "bank-115",
    body: "Ktoré mesto bolo sídlom Slovenskej národnej rady počas SNP v rokoch 1944–1945?",
    answer: "Banská Bystrica",
    options: ["Bratislava", "Košice", "Banská Bystrica", "Žilina", "Prešov", "Martin"],
    correctIndex: 2,
    difficulty: 6,
    note: "Košice boli oslobodené skôr (1945), SNP centrum bolo Bystrica. Bratislava zostala okupovaná — klasická pasca pre tých, čo spájajú SNP s hlavným mestom.",
    tags: ["história", "slovensko"],
  },
  {
    id: "bank-116",
    body: "Ktorý český skladateľ zložil operu Prodaná nevesta (1866)?",
    answer: "Bedřich Smetana",
    options: ["Antonín Dvořák", "Bedřich Smetana", "Leoš Janáček", "Bohuslav Martinů", "Josef Suk", "Zdeněk Fibich"],
    correctIndex: 1,
    difficulty: 6,
    note: "Dvořák má Rusalku, Janáček Její pastorkyňa. Prodaná nevesta = Smetana, premiéra v Prozatímním divadle v Prahe.",
    tags: ["hudba", "česko"],
  },
  {
    id: "bank-117",
    body: "Ktorá rieka je najdlhšia výhradne na území Slovenska?",
    answer: "Váh",
    options: ["Dunaj", "Tisa", "Váh", "Hron", "Morava", "Poprad"],
    correctIndex: 2,
    difficulty: 7,
    note: "Dunaj je dlhší, ale tečie cez viac krajín. Váh (~403 km) je najdlhší tok, ktorý zostáva celý na Slovensku — Morava je kratšia.",
    tags: ["geografia", "slovensko"],
  },
  {
    id: "bank-118",
    body: "Ktorý slovenský režisér spolurežíroval film Obchod na korze (1965), držiteľa Oscara za cudzí jazykový film?",
    answer: "Ján Kadár",
    options: ["Ján Kadár", "Štefan Uher", "Martin Hollý", "Juraj Jakubisko", "Dušan Hanák", "Peter Solan"],
    correctIndex: 0,
    difficulty: 8,
    note: "Kadár natočil film s Elmarom Klosom v Prahe. Jakubisko a Hollý sú slávnejší doma, ale Oscar patrí Kadárovi.",
    tags: ["film", "slovensko"],
  },
  {
    id: "bank-119",
    body: "Aký destilát je hlavnou zložkou klasického koktailu Negroni?",
    answer: "Gin",
    options: ["Gin", "Vodka", "Rum", "Tequila", "Whiskey", "Brandy"],
    correctIndex: 0,
    difficulty: 6,
    note: "Negroni = gin + Campari + sweet vermouth. Tipuje sa Aperol Spritz (iný drink) alebo whiskey (Old Fashioned).",
    tags: ["alkohol", "koktaily"],
  },
  {
    id: "bank-120",
    body: "Ktoré zviera má modrú krv vďaka hemocyanínu namiesto hemoglobínu?",
    answer: "Pátrací krab (Limulus)",
    options: ["Humr", "Krab", "Pátrací krab (Limulus)", "Chobotnica", "Sépiu", "Medúza"],
    correctIndex: 2,
    difficulty: 8,
    note: "Chobotnica má modrú krv tiež, ale otázka cieli na „živú fosíliu“ Limulus — medicínsky testy na endotoxíny. Humr má modrú len pri určitých stavoch.",
    tags: ["zvieratá", "medicína"],
  },
  {
    id: "bank-121",
    body: "V ktorom roku bola založená spoločnosť IKEA Ingvarom Kampradom?",
    answer: "1943",
    options: ["1933", "1943", "1953", "1963", "1973", "1923"],
    correctIndex: 1,
    difficulty: 8,
    note: "Prvá predajňa nábytku až 1958 v Älmhulte. 1943 = založenie ako obchod s poštovými zásielkami — pub pasca je tipovať rok otvorenia obchodu.",
    tags: ["ekonomika", "ikea"],
  },
  {
    id: "bank-122",
    body: "Ktorý český panovník nechal postaviť Karlštejn na ochranu korunovačných klenotov?",
    answer: "Karel IV.",
    options: ["Václav II.", "Karel IV.", "Přemysl Otakar II.", "Václav IV.", "Jiří z Poděbrad", "Rudolf II."],
    correctIndex: 1,
    difficulty: 7,
    note: "Otakar II. staval Zvikov a Bezděz, Rudolf II. sa preslávil Prahou. Karlštejn (1348–1365) = Karel IV.",
    tags: ["história", "česko"],
  },
  {
    id: "bank-123",
    body: "Ktorá krajina má v Európe najviac priamych susedov (hraničí s 9 štátmi)?",
    answer: "Nemecko",
    options: ["Poľsko", "Francúzsko", "Nemecko", "Rakúsko", "Ukrajina", "Taliansko"],
    correctIndex: 2,
    difficulty: 7,
    note: "Poľsko má 7 susedov, Francúzsko 8 (vrátane monastických enkláv). Nemecko = 9 — Dánsko cez most sa nepočíta.",
    tags: ["geografia", "nemecko"],
  },
  {
    id: "bank-124",
    body: "Ktorý film režiséra Quentina Tarantina získal Palmu zlato v Cannes 1994?",
    answer: "Pulp Fiction",
    options: ["Reservoir Dogs", "Pulp Fiction", "Jackie Brown", "Kill Bill", "Django Unchained", "Inglourious Basterds"],
    correctIndex: 1,
    difficulty: 7,
    note: "Reservoir Dogs bol v Sundance, Palma = Pulp Fiction. Kill Bill prišiel o dekádu neskôr.",
    tags: ["film", "tarantino"],
  },
  {
    id: "bank-125",
    body: "Aký typ piva je český ležiak Pilsner Urquell?",
    answer: "Svetlý ležiak (pilsner)",
    options: ["Tmavý ležiak", "Polotmavý ležiak", "Světlý ležiak (pilsner)", "IPA", "Stout", "Porter"],
    correctIndex: 2,
    difficulty: 6,
    note: "Plzeň 1842 = svetlý spodne kvasený ležiak. Tipuje sa tmavé pivo kvôli „Urquell“ zvučnému názvu.",
    tags: ["alkohol", "česko"],
  },
  {
    id: "bank-126",
    body: "Ktorý grécky boh je považovaný za boha mora, zemetrasení a koní?",
    answer: "Poseidón",
    options: ["Zeus", "Hádes", "Poseidón", "Hermes", "Apollo", "Ares"],
    correctIndex: 2,
    difficulty: 6,
    note: "Zeus = nebo, Hádes = podsvetie. Poseidón drží trojzubec — v Ríme bol Neptún, čo mätie pub tím.",
    tags: ["mýty", "grécko"],
  },
  {
    id: "bank-127",
    body: "V ktorom roku schválila Národná rada SR Ústavu Slovenskej republiky?",
    answer: "1992",
    options: ["1990", "1991", "1992", "1993", "1994", "1989"],
    correctIndex: 2,
    difficulty: 7,
    note: "Samostatnosť vyhlásená 1. 1. 1993, ale ústava schválená už 1. 9. 1992 — pub pasca je tipovať rok vyhlásenia nezávislosti.",
    tags: ["politika", "slovensko"],
  },
  {
    id: "bank-128",
    body: "Na ktorej slovenskej banke bol pred zavedením eura portrét Antona Bernoláka?",
    answer: "100 slovenských korún",
    options: ["20 Sk", "50 Sk", "100 Sk", "200 Sk", "500 Sk", "1000 Sk"],
    correctIndex: 2,
    difficulty: 8,
    note: "20 Sk = Jánošík, 1000 Sk = Štúr. Bernolák na stovke — jazykový reformátor, nie zakladateľ štátu.",
    tags: ["ekonomika", "slovensko"],
  },
  {
    id: "bank-129",
    body: "Ktorý internetový vyhľadávač bol pôvodne nazývaný „BackRub“?",
    answer: "Google",
    options: ["Yahoo", "Google", "AltaVista", "Bing", "Ask Jeeves", "Lycos"],
    correctIndex: 1,
    difficulty: 8,
    note: "BackRub bol interný názov pred premenovaním na Google (1997). Otázka nie je o roku založenia — pasca je tipovať Yahoo.",
    tags: ["internet", "technológia"],
  },
  {
    id: "bank-130",
    body: "Ktorá televízna relácia Dr. House sa odohráva v nemocnici Princeton–Plainsboro Teaching Hospital?",
    answer: "House M.D.",
    options: ["Grey's Anatomy", "House M.D.", "ER", "Scrubs", "The Good Doctor", "Chicago Med"],
    correctIndex: 1,
    difficulty: 6,
    note: "Grey's = Seattle Grace, ER = Chicago County. House = diagnostika, laska po chodidlách — ikonický pub tip.",
    tags: ["televízia", "seriály"],
  },
  {
    id: "bank-131",
    body: "Ktoré mesto hostilo Zimné olympijské hry 1984?",
    answer: "Sarajevo",
    options: ["Innsbruck", "Sarajevo", "Calgary", "Lillehammer", "Sapporo", "Lake Placid"],
    correctIndex: 1,
    difficulty: 7,
    note: "Innsbruck mal 1964 a 1976, Lake Placid 1980. Sarajevo 1984 — pred vojnou v Juhoslávií, často tipujú Innsbruck.",
    tags: ["šport", "olympiáda"],
  },
  {
    id: "bank-132",
    body: "Ktorý slovenský hokejista vyhral Stanley Cup s tímom Pittsburgh Penguins v roku 1991?",
    answer: "Peter Šťastný",
    options: ["Miroslav Šatan", "Peter Šťastný", "Marián Hossa", "Zdeno Chára", "Milan Hejduk", "Miroslav Iglódy"],
    correctIndex: 1,
    difficulty: 8,
    note: "Hossa vyhral neskôr (2010, 2013), Šatan nikdy. Peter Šťastný s Penguins 1991 — prvý Slovák s pohárom.",
    tags: ["šport", "slovensko"],
  },
  {
    id: "bank-133",
    body: "Ktorý český spisovateľ napísal román Spalovač mrtvol?",
    answer: "Ladislav Fuks",
    options: ["Bohumil Hrabal", "Ladislav Fuks", "Milan Kundera", "Jaroslav Hašek", "Karel Čapek", "Ivan Klíma"],
    correctIndex: 1,
    difficulty: 8,
    note: "Hrabal = Ostře sledované vlaky, Hašek = Švejk. Fuks — groteska o krematóriu, menej známa, ale ikonická.",
    tags: ["literatúra", "česko"],
  },
  {
    id: "bank-134",
    body: "Ktorá planéta Slnečnej sústavy má najviac potvrdených mesiacov (2023+)?",
    answer: "Saturn",
    options: ["Jupiter", "Saturn", "Urán", "Neptún", "Mars", "Zem"],
    correctIndex: 1,
    difficulty: 8,
    note: "Dlhodobo tipovali Jupiter (~95), nové objavy okolo Saturnu ho prekonali (145+). Pub otázka sa mení — Saturn momentálne vedie.",
    tags: ["astronómia", "saturn"],
  },
  {
    id: "bank-135",
    body: "Aký je hlavný syrový ingredient tradičného švajčiarskeho fondue?",
    answer: "Gruyère (s Emmentaler alebo inými)",
    options: ["Cheddar", "Gouda", "Gruyère (s Emmentaler alebo inými)", "Parmezán", "Brie", "Feta"],
    correctIndex: 2,
    difficulty: 7,
    note: "Cheddar = anglický pub, Parmezán = taliansky. Klasické fondue = gruyère + emmentaler + biely wine + kirsch.",
    tags: ["jedlo", "švajčiarsko"],
  },
  {
    id: "bank-136",
    body: "Ktorý slovenský politik bol prvým predsedom vlády samostatného Slovenska po roku 1993?",
    answer: "Vladimír Mečiar",
    options: ["Michal Kováč", "Vladimír Mečiar", "Mikuláš Dzurinda", "Jozef Moravčík", "Ivan Gašparovič", "Robert Fico"],
    correctIndex: 1,
    difficulty: 7,
    note: "Kováč bol prezident, Dzurinda prišiel 1998. Mečiar viedol vládu od vyhlásenia nezávislosti.",
    tags: ["politika", "slovensko"],
  },
  {
    id: "bank-137",
    body: "Ktorá architektonická pamiatka v Barcelone je stále nedostavaná od začiatku výstavby v roku 1882?",
    answer: "Sagrada Família",
    options: ["Casa Batlló", "Sagrada Família", "Casa Milà", "Palau Güell", "Park Güell", "Montjuïc"],
    correctIndex: 1,
    difficulty: 6,
    note: "Gaudího chrám stále rastie — dokončenie plánované v 2020-tych rokoch. Batlló a Milà sú hotové domy.",
    tags: ["architektúra", "španielsko"],
  },
  {
    id: "bank-138",
    body: "Ktorá stolová hra používa figúrky v tvare koní, veží, strelcov a kráľa na 64 poliach?",
    answer: "Šach",
    options: ["Dáma", "Šach", "Go", "Shogi", "Backgammon", "Halma"],
    correctIndex: 1,
    difficulty: 6,
    note: "Dáma má len jeden typ figúrky, Go má kamene. 64 polí + rôzne figúrky = šach — znie ľahko, ale mätie s dámou.",
    tags: ["hry", "šach"],
  },
  {
    id: "bank-139",
    body: "Ktorý český hokejový brankár vyhral Vezina Trophy v NHL ako prvý Európan?",
    answer: "Dominik Hašek",
    options: ["Jaromír Jágr", "Dominik Hašek", "Milan Hejduk", "Pavel Bure", "Miroslav Šatan", "Tomáš Plekanec"],
    correctIndex: 1,
    difficulty: 8,
    note: "Jágr je útočník. Hašek získal Vezinu viackrát (1994, 1995, 1997, 1998, 2001) — „Dominátor“.",
    tags: ["šport", "česko"],
  },
  {
    id: "bank-140",
    body: "Ktoré zviera dokáže spanikovať pri vysokom obsahu kofeínu a zomrieť na srdcové zlyhanie (typický domáci miláčik)?",
    answer: "Pes",
    options: ["Mačka", "Pes", "Králik", "Morča", "Korytnačka", "Papagáj"],
    correctIndex: 1,
    difficulty: 8,
    note: "Mačka je citlivejšia na teobromín v čokoláde, ale čokoláda + kofeín u psov je smrteľná kombinácia — časté veterné varovanie.",
    tags: ["zvieratá", "medicína"],
  },
  {
    id: "bank-141",
    body: "Ktorý slovenský národný park je najstarší (vyhlásený 1949)?",
    answer: "Tatranský národný park (TANAP)",
    options: ["NAPANT", "TANAP", "PIENAP", "NP Nízke Tatry", "NP Malá Fatra", "NP Slovenský raj"],
    correctIndex: 1,
    difficulty: 7,
    note: "Slovenský raj je známejší turistom, ale TANAP vznikol ako prvý v Československu v roku 1949.",
    tags: ["geografia", "slovensko"],
  },
  {
    id: "bank-142",
    body: "Ktorý režisér natočil film Blade Runner (1982)?",
    answer: "Ridley Scott",
    options: ["Steven Spielberg", "Ridley Scott", "James Cameron", "George Lucas", "John Carpenter", "David Lynch"],
    correctIndex: 1,
    difficulty: 7,
    note: "Cameron = Terminator, Lucas = Star Wars. Scott = sci-fi vizuál (Alien, Blade Runner). Lynch robil Dune (1984).",
    tags: ["film", "sci-fi"],
  },
  {
    id: "bank-143",
    body: "Aký alkohol je tradičnou základnou zložkou mexického drinku Paloma?",
    answer: "Tequila",
    options: ["Tequila", "Mezcal", "Rum", "Gin", "Vodka", "Pisco"],
    correctIndex: 0,
    difficulty: 7,
    note: "Paloma = tequila + grapefruitová soda (Squirt/T Jarritos). Margarita je tiež tequila, ale s limetkou — mätie pub.",
    tags: ["alkohol", "mexiko"],
  },
  {
    id: "bank-144",
    body: "Ktorý slovenský múzejný areál v Banskej Štiavnici je súčasťou UNESCO baníckeho mesta?",
    answer: "Open-air mining museum (Starý a Nový hrad)",
    options: ["Vlkolínec", "Open-air mining museum (Starý a Nový hrad)", "Betliar", "Brhlovce", "Červený Kláštor", "Hronsek"],
    correctIndex: 1,
    difficulty: 8,
    note: "Vlkolínec je dedinka, Betliar kaštieľ. Banícky skanzen a hrad v Štiavnici = jadro UNESCO lokality.",
    tags: ["história", "slovensko"],
  },
  {
    id: "bank-145",
    body: "Ktorá krajina vyrobila ako prvá komerčný jadrový reaktor pre civilné využitie (Obninsk 1954)?",
    answer: "Sovietsky zväz (SSSR)",
    options: ["USA", "Veľká Británia", "Sovietsky zväz (SSSR)", "Francúzsko", "Kanada", "Nemecko"],
    correctIndex: 2,
    difficulty: 9,
    note: "USA mali prvú bombu a neskôr Shippingport (1957). Obninsk v ZSSR 1954 = prvá elektráreň pre sieť.",
    tags: ["technológia", "energetika"],
  },
  {
    id: "bank-146",
    body: "Ktorý český skladateľ zložil cyklus symfónií Má vlast?",
    answer: "Bedřich Smetana",
    options: ["Antonín Dvořák", "Bedřich Smetana", "Leoš Janáček", "Bohuslav Martinů", "Josef Bohuslav Foerster", "Vítězslav Novák"],
    correctIndex: 1,
    difficulty: 7,
    note: "Dvořák má Novosvetskú (9.), ale Má vlast (Vltava!) = Smetana. Janáček je moravský modernista.",
    tags: ["hudba", "česko"],
  },
  {
    id: "bank-147",
    body: "Ktoré mesto je známe pôvodom syra Roquefort (modré plesne)?",
    answer: "Roquefort-sur-Soulzon (Francúzsko)",
    options: ["Gouda (Holandsko)", "Roquefort-sur-Soulzon (Francúzsko)", "Parma (Taliansko)", "Gruyères (Švajčiarsko)", "Cheddar (Anglicko)", "Brie (Francúzsko)"],
    correctIndex: 1,
    difficulty: 7,
    note: "Gouda a Cheddar sú tvrdé/tvrdnúce syry bez modrej plesne. Roquefort = ovčí syr v jaskyniach Aveyron.",
    tags: ["jedlo", "francúzsko"],
  },
  {
    id: "bank-148",
    body: "Ktorý slovenský futbalový klub hral v sezóne 2023/24 skupinu Európskej konferenčnej ligy?",
    answer: "Spartak Trnava",
    options: ["Slovan Bratislava", "Spartak Trnava", "Žilina", "Trenčín", "Ružomberok", "DAC Dunajská Streda"],
    correctIndex: 1,
    difficulty: 8,
    note: "Slovan hrával skôr Ligu majstrov, v 2023/24 Trnava reprezentoval v konferenčnej — mení sa podľa sezóny, pub tip na „najväčší“ klub.",
    tags: ["šport", "slovensko"],
  },
  {
    id: "bank-149",
    body: "Ktorý grécky hrdina zabil Minotaura v labyrinte na Kréte?",
    answer: "Thézeus",
    options: ["Herakles", "Thézeus", "Achilles", "Perseus", "Odysseus", "Jason"],
    correctIndex: 1,
    difficulty: 6,
    note: "Herakles mal 12 prác, Perseus Medúzu. Thézeus + Ariadnina niť = Minotauros. Odysseus = Trója.",
    tags: ["mýty", "grécko"],
  },
  {
    id: "bank-150",
    body: "Ktorá krajina má najviac jazykov s úradným statusom podľa indickej ústavy (8. plán)?",
    answer: "India (22 scheduled languages)",
    options: ["India (22 scheduled languages)", "Švajčiarsko", "Južná Afrika", "Kanada", "Etiópia", "Nigéria"],
    correctIndex: 0,
    difficulty: 8,
    note: "Švajčiarsko má 4, Južná Afrika 11. India má 22 ústavne uznávaných jazykov — pub pasca je tipovať Afriku.",
    tags: ["geografia", "india"],
  },
  {
    id: "bank-151",
    body: "Ktorý slovenský herec stvárnil Jánošíka vo filme Jánošík (1963, režia Paľo Bielik)?",
    answer: "Michal Dočolomanský",
    options: ["Michal Dočolomanský", "Jozef Kroner", "Štefan Kvietik", "Juraj Kukura", "Marián Labuda", "Martin Huba"],
    correctIndex: 0,
    difficulty: 8,
    note: "Kvietik hral Jánošíka v staršej verzii (1962 František Zvarík). Dočolomanský = ikonický Bielikov Jánošík 1963.",
    tags: ["film", "slovensko"],
  },
  {
    id: "bank-152",
    body: "Ktorý cicavec má najviac zubov (bežný delfín až približne 260)?",
    answer: "Delfín (common dolphin)",
    options: ["Slon", "Opossum", "Delfín (common dolphin)", "Nílsky krokodíl", "Žralok biely", "Pes"],
    correctIndex: 2,
    difficulty: 9,
    note: "Žralok má viac zubov, ale nie je cicavec. Medzi cicavcami vedie delfín — opossum má len okolo 50, slon 26.",
    tags: ["zvieratá", "oceán"],
  },
  {
    id: "bank-153",
    body: "V ktorom roku bola spustená prvá verzia webového prehliadača Mosaic?",
    answer: "1993",
    options: ["1989", "1991", "1993", "1995", "1997", "1999"],
    correctIndex: 2,
    difficulty: 9,
    note: "World Wide Web 1989, Netscape 1994. Mosaic (1993) = prvý populárny grafický browser — predchodca Netscape.",
    tags: ["internet", "história"],
  },
  {
    id: "bank-154",
    body: "Ktorý český film získal Oscara za najlepší cudzojazyčný film v roku 1996?",
    answer: "Kolya (Kolja)",
    options: ["Kolya (Kolja)", "Closely Watched Trains", "Amadeus", "The Shop on Main Street", "The Firemen's Ball", "Divided We Fall"],
    correctIndex: 0,
    difficulty: 8,
    note: "Amadeus je americký film Formana. Kolja (Jan Svěrák) 1996 — pub pasca je tipovať staršie československé klasiky.",
    tags: ["film", "česko"],
  },
  {
    id: "bank-155",
    body: "Ktorá európska krajina má najvyšší počet hradov a zrúcanín na km² (často uvádzaný rekord)?",
    answer: "Wales",
    options: ["Škótsko", "Wales", "Írsko", "Francúzsko", "Nemecko", "Slovensko"],
    correctIndex: 1,
    difficulty: 9,
    note: "Škótsko má viac hradov celkovo, ale Wales má najvyššiu hustotu (~600+). Slovensko je v hre, ale rekord patrí Walesu.",
    tags: ["geografia", "wales"],
  },
  {
    id: "bank-156",
    body: "Ktorý slovenský maliar je autorom obrazu Zjavenie (1925)?",
    answer: "Martin Benka",
    options: ["Martin Benka", "Ladislav Medňanský", "Mikuláš Galanda", "Imro Weiner-Kráľ", "Janko Alexy", "Miloš Alexander Bazovský"],
    correctIndex: 0,
    difficulty: 9,
    note: "Medňanský je modernista v Paríži, Bazovský = krajina. Benka = slovenská krajina a Zjavenie — školská, v pube menej známa.",
    tags: ["výtvarníctvo", "slovensko"],
  },
  {
    id: "bank-157",
    body: "Aký typ alkoholu je základom tradičného peruánskeho drinku Pisco Sour?",
    answer: "Pisco (hroznový destilát)",
    options: ["Pisco (hroznový destilát)", "Tequila", "Cachaça", "Rum", "Grappa", "Sake"],
    correctIndex: 0,
    difficulty: 7,
    note: "Cachaça = Brazília (Caipirinha). Pisco = Peru/Chile — Pisco Sour s citrónom a angosturou.",
    tags: ["alkohol", "peru"],
  },
  {
    id: "bank-158",
    body: "Ktorý český filozof a matematik vynašiel moderné kontaktné šošovky z HEMA gél-u (1961)?",
    answer: "Otto Wichterle",
    options: ["Jan Hus", "Otto Wichterle", "Tomáš Garrigue Masaryk", "Karel Čapek", "Jaroslav Heyrovský", "Ludvík Očenášek"],
    correctIndex: 1,
    difficulty: 8,
    note: "Heyrovský = polarografia (Nobelova). Wichterle doma v Plzeňskom ristoráne vymodeloval prvé mäkké šošovky.",
    tags: ["medicína", "česko"],
  },
  {
    id: "bank-159",
    body: "Ktorá televízna stanica vypustila seriál Breaking Bad (2008)?",
    answer: "AMC",
    options: ["HBO", "AMC", "Netflix", "FX", "Showtime", "ABC"],
    correctIndex: 1,
    difficulty: 7,
    note: "HBO má Sopranos/Wire, Netflix seriál až neskôr streamoval. Breaking Bad = AMC cable.",
    tags: ["televízia", "seriály"],
  },
  {
    id: "bank-160",
    body: "Ktoré mesto je známe kaštieľom, ktorý bol sídlom rodiny Andrássyovcov a je na UNESCO zozname?",
    answer: "Betliar",
    options: ["Betliar", "Bojnice", "Orava", "Smolenice", "Topoľčianky", "Oponice"],
    correctIndex: 0,
    difficulty: 8,
    note: "Bojnice je najnavštevovanejší, ale UNESCO kaštieľ s knižnicou = Betliar. Orava je hrad, nie kaštieľ.",
    tags: ["architektúra", "slovensko"],
  },
  {
    id: "bank-161",
    body: "Ktorý organ v ľudskom tele má schopnosť samostatnej regenerácie až do 75 % hmotnosti?",
    answer: "Pečeň",
    options: ["Oblička", "Pečeň", "Srdce", "Pľúca", "Slezeň", "Žalúdok"],
    correctIndex: 1,
    difficulty: 7,
    note: "Oblička sa neobnoví celá, srdce jazvuje. Pečeň dokáže dorásť — dôvod, prečo funguje darcovstvo žijúceho darcu.",
    tags: ["medicína", "anatómia"],
  },
  {
    id: "bank-162",
    body: "Ktorý slovenský režisér natočil dokumentárny film Obrazy starého sveta (1972)?",
    answer: "Dušan Hanák",
    options: ["Dušan Hanák", "Martin Hollý", "Juraj Jakubisko", "Peter Solan", "Štefan Uher", "Ján Kadár"],
    correctIndex: 0,
    difficulty: 8,
    note: "Hanák = poetický dokument o starých ľuďoch na vidieku. Hollý natočil hraný film Vlk a pes — častá zámiena v pub kvíze.",
    tags: ["film", "slovensko"],
  },
  {
    id: "bank-163",
    body: "Ktorý vrch je najvyšší v Nízkych Tatrách?",
    answer: "Dumbier (2043 m n. m.)",
    options: ["Chopok", "Dumbier (2043 m n. m.)", "Kráľova hoľa", "Ďumbier", "Rakytov", "Prašivá"],
    correctIndex: 1,
    difficulty: 7,
    note: "Chopok má lanovku a lyžovanie — tipuje sa častejšie. Dumbier je o pár metrov vyšší a geograficky vrchol pohoria.",
    tags: ["geografia", "slovensko"],
  },
  {
    id: "bank-164",
    body: "Ktorý český kráľ bol známy ako „Riešiteľ otázok českého státu“ a bol posledným z rodu Přemyslovcov?",
    answer: "Václav III.",
    options: ["Václav II.", "Václav III.", "Karel IV.", "Jan Lucemburský", "Václav I.", "Otakar II."],
    correctIndex: 1,
    difficulty: 8,
    note: "Karel IV. je najslávnejší, ale Přemyslovci skončili vraždou Václava III. v Olomouci 1306.",
    tags: ["história", "česko"],
  },
  {
    id: "bank-165",
    body: "Ktorá hra od Nintendo má postavičku Linka a princeznú Zeld?",
    answer: "The Legend of Zelda",
    options: ["Super Mario", "The Legend of Zelda", "Metroid", "Pokémon", "Kirby", "Donkey Kong"],
    correctIndex: 1,
    difficulty: 6,
    note: "Mario = skokán, Metroid = Samus. Link ≠ Zelda — princezná je meno, nie hrdina (pub vtip).",
    tags: ["hry", "nintendo"],
  },
  {
    id: "bank-166",
    body: "Ktorý slovenský tenista dosiahol v roku 2016 kariérne najvyššie ATP poradie okolo 14. miesta?",
    answer: "Martin Kližan",
    options: ["Dominik Hrbatý", "Martin Kližan", "Karol Kučera", "Andrej Martin", "Jozef Kovalík", "Norbert Gombos"],
    correctIndex: 1,
    difficulty: 9,
    note: "Hrbatý bol skôr (2004 top 12), Kližan 2015–16 peak. Pub pasca: tipovať Hrbatého bez roka.",
    tags: ["šport", "slovensko"],
  },
  {
    id: "bank-167",
    body: "Ktoré mesto je domovom pivovaru Guinness a skladu na ulici St. James's Gate?",
    answer: "Dublin",
    options: ["Cork", "Dublin", "Galway", "Belfast", "Limerick", "Edinburgh"],
    correctIndex: 1,
    difficulty: 6,
    note: "Cork = Murphy's, Belfast je Severné Írsko. Guinness Storehouse = Dublin od 1759.",
    tags: ["alkohol", "írsko"],
  },
  {
    id: "bank-168",
    body: "Ktorý film získal Oscara za najlepší film na ceremónii v roku 2020 (filmy z 2019)?",
    answer: "Parasite",
    options: ["1917", "Parasite", "Joker", "Once Upon a Time in Hollywood", "The Irishman", "Little Women"],
    correctIndex: 1,
    difficulty: 7,
    note: "1917 vyhralo kameru, Joker herca. Parasite = prvý neanglický film s Oscarom za najlepší film.",
    tags: ["film", "kórea"],
  },
  {
    id: "bank-169",
    body: "Ktorý slovenský skladateľ je autorom opery Krútňava?",
    answer: "Eugen Suchoň",
    options: ["Eugen Suchoň", "Ján Cikker", "Alexander Moyzes", "Mikuláš Schneider-Trnavský", "Dezider Kardoš", "Ilja Zeljenka"],
    correctIndex: 0,
    difficulty: 8,
    note: "Cikker = Juro Jánošík, Moyzes symfónie. Krútňava (1949–1953) = Suchoň, slovenská operná klasika.",
    tags: ["hudba", "slovensko"],
  },
  {
    id: "bank-170",
    body: "Ktorá krajina má na svete najviac aktívnych sopiek?",
    answer: "Indonézia",
    options: ["Japonsko", "Indonézia", "Island", "Taliansko", "Chile", "USA"],
    correctIndex: 1,
    difficulty: 8,
    note: "Japonsko je mediálne známe (Fudži), ale Indonézia má v Pacifickom ohnivom prstenci viac než 120 aktívnych sopiek.",
    tags: ["geografia", "indonézia"],
  },
  {
    id: "bank-171",
    body: "Ktorý český spisovateľ napísal román Ostře sledované vlaky?",
    answer: "Bohumil Hrabal",
    options: ["Jaroslav Hašek", "Bohumil Hrabal", "Milan Kundera", "Karel Čapek", "Ladislav Fuks", "Ivan Klíma"],
    correctIndex: 1,
    difficulty: 7,
    note: "Hašek = Švejk, Kundera = Nesnesiteľná ľahkosť. Hrabal — parná lokomotíva a sexualita za 2. sv. vojny.",
    tags: ["literatúra", "česko"],
  },
  {
    id: "bank-172",
    body: "Ktoré zviera má najdlhší obdobie gravidity spomedzi cicavcov (až 22 mesiacov)?",
    answer: "Slonica (africký slon)",
    options: ["Veľryba", "Slonica (africký slon)", "Žirafa", "Nosorožec", "Kôň", "Hroch"],
    correctIndex: 1,
    difficulty: 7,
    note: "Veľryby majú dlhé gravidity tiež, ale medzi suchozemskými cicavcami vedie slon ~22 mesiacov. Žirafa ~15 mes.",
    tags: ["zvieratá", "safari"],
  },
  {
    id: "bank-173",
    body: "Ktorý slovenský politik podpísal Martinskú deklaráciu v roku 1861 ako jeden z lídrov?",
    answer: "Ján Francisci-Rimavský",
    options: ["Ľudovít Štúr", "Milan Rastislav Štefánik", "Ján Francisci-Rimavský", "Anton Bernolák", "Jozef Miloslav Hurban", "Samuel Zoch"],
    correctIndex: 2,
    difficulty: 9,
    note: "Štúr zomrel 1856, Štefánik ešte nežil. Martinská deklarácia 1861 — tipuje sa Štúr, ale to bol už iný generation.",
    tags: ["história", "slovensko"],
  },
  {
    id: "bank-174",
    body: "Ktorá planéta má najkratší deň (najrýchlejšia rotácia)?",
    answer: "Jupiter",
    options: ["Mars", "Zem", "Jupiter", "Saturn", "Urán", "Neptún"],
    correctIndex: 2,
    difficulty: 7,
    note: "Jupiter ~9,9 h. Saturn je blízko, ale pomalší. Zem 24 h — pub pasca je tipovať najväčšiu planétu Saturn.",
    tags: ["astronómia", "planéty"],
  },
  {
    id: "bank-175",
    body: "Ktorý typ vína je základom francúzskeho aperitívu Kir?",
    answer: "Biele víno (Aligoté) + crème de cassis",
    options: ["Červené víno", "Biele víno (Aligoté) + crème de cassis", "Šampanské", "Portské", "Rosé", "Sherry"],
    correctIndex: 1,
    difficulty: 8,
    note: "Kir Royal = so šampanským. Klasický Kir = biele burgundské + čierne ríbezle likér.",
    tags: ["alkohol", "francúzsko"],
  },
  {
    id: "bank-176",
    body: "Ktorý slovenský hokejový brankár mal prezývku „Bodka“ a pôsobil v NHL?",
    answer: "Ján Laco",
    options: ["Ján Laco", "Jaroslav Janus", "Zdeno Macejko", "Rastislav Staňa", "Adam Huska", "Marek Čiliak"],
    correctIndex: 0,
    difficulty: 9,
    note: "Laco hral krátko v NHL (Detroit), prezývka Bodka. Čiliak je známejší v Európe — pub otázka pre fanúšikov.",
    tags: ["šport", "slovensko"],
  },
  {
    id: "bank-177",
    body: "Ktorá architektonická pamiatka v Ríme je najväčším neopakovane používaným antickým amfiteátrom?",
    answer: "Koloseum (Flavijský amfiteáter)",
    options: ["Pantheon", "Koloseum (Flavijský amfiteáter)", "Circus Maximus", "Forum Romanum", "Trajanov stĺp", "Caracalla"],
    correctIndex: 1,
    difficulty: 6,
    note: "Circus Maximus je väčší areál, ale amfiteáter s arénou = Koloseum. Pantheon = chrám, nie aréna.",
    tags: ["architektúra", "rím"],
  },
  {
    id: "bank-178",
    body: "Ktorý český režisér natočil film Pelíšky (1999)?",
    answer: "Jan Hřebejk",
    options: ["Jan Hřebejk", "Jan Svěrák", "Miloš Forman", "Jiří Menzel", "Věra Chytilová", "Petr Zelenka"],
    correctIndex: 0,
    difficulty: 8,
    note: "Svěrák = Kolja, Forman = Amadeus. Pelíšky = Hřebejk, vianočná tragikomédia okolo okupácie 1968.",
    tags: ["film", "česko"],
  },
  {
    id: "bank-179",
    body: "Ktoré zviera je schopné prežiť vo vesmíre bez ochrany (vákuum, radiácia) niekoľko dní?",
    answer: "Medvedík vodný (tardigrade)",
    options: ["Kakat", "Medvedík vodný (tardigrade)", "Skorpion", "Kaktusový vretenec", "Púštny chrobák", "Kreveta"],
    correctIndex: 1,
    difficulty: 7,
    note: "Tardigrade = extremofil, „vodný medvedík“. Skorpion prežije radiáciu, ale nie otvorené vákuum dlhodobo.",
    tags: ["zvieratá", "extremofily"],
  },
  {
    id: "bank-180",
    body: "Ktorý slovenský múzejný skanzen vo Vlkolínci je na UNESCO zozname od roku 1993?",
    answer: "Vlkolínec",
    options: ["Vlkolínec", "Čičmany", "Brhlovce", "Špania Dolina", "Podbiel", "Sebechleby"],
    correctIndex: 0,
    difficulty: 7,
    note: "Čičmany majú maľované domy, ale UNESCO dedina = Vlkolínec. Brhlovce = skalné domy, iný zoznam.",
    tags: ["geografia", "slovensko"],
  },
  {
    id: "bank-181",
    body: "Ktorá kryptomena bola vytvorená pseudonymným Satoshi Nakamotom v roku 2009?",
    answer: "Bitcoin",
    options: ["Ethereum", "Bitcoin", "Litecoin", "Ripple", "Dogecoin", "Monero"],
    correctIndex: 1,
    difficulty: 6,
    note: "Ethereum 2015 (Vitalik). Bitcoin genesis block 3. 1. 2009 — prvá decentralizovaná mena.",
    tags: ["ekonomika", "kryptomeny"],
  },
  {
    id: "bank-182",
    body: "Ktorý slovenský režisér natočil film Vlk a pes (1982)?",
    answer: "Martin Hollý",
    options: ["Martin Hollý", "Juraj Jakubisko", "Dušan Hanák", "Štefan Uher", "Peter Solan", "Ján Kadár"],
    correctIndex: 0,
    difficulty: 8,
    note: "Jakubisko = Perinbaba, Hanák = Obrazy starého sveta. Vlk a pes = Hollý, drsná dráma v horách.",
    tags: ["film", "slovensko"],
  },
  {
    id: "bank-183",
    body: "Ktorý grécky boh zosielal blesky a bol najvyšší na Olympu?",
    answer: "Zeus",
    options: ["Poseidón", "Hádes", "Zeus", "Apollo", "Ares", "Hermes"],
    correctIndex: 2,
    difficulty: 6,
    note: "Jednoduché, ale v pube sa mätie s Jupiterom (Rím) alebo Thorom (severská mytológia).",
    tags: ["mýty", "grécko"],
  },
  {
    id: "bank-184",
    body: "Ktoré mesto je známe festivalom Oktoberfest (pôvodne svadobná oslava 1810)?",
    answer: "Mníchov",
    options: ["Berlín", "Mníchov", "Kolín nad Rýnom", "Frankfurt", "Hamburg", "Viedeň"],
    correctIndex: 1,
    difficulty: 6,
    note: "Kolín = Kölsch pivo, Viedeň = vinohrady. Oktoberfest = Theresienwiese v Mníchove.",
    tags: ["alkohol", "nemecko"],
  },
  {
    id: "bank-185",
    body: "Ktorý český hokejista nosil v NHL slávne číslo 68?",
    answer: "Jaromír Jágr",
    options: ["Jaromír Jágr", "Dominik Hašek", "Mario Lemieux", "Milan Hejduk", "Patrik Eliáš", "Robert Lang"],
    correctIndex: 0,
    difficulty: 6,
    note: "68 = rok okupácie Československa, Jágr to dal vedome. Hejduk mal 23, Hašek 39.",
    tags: ["šport", "česko"],
  },
  {
    id: "bank-186",
    body: "Ktorá slovenská rieka sa vlieva do Dunaja pri Štúrove?",
    answer: "Hron",
    options: ["Váh", "Hron", "Nitra", "Morava", "Ipeľ", "Hornád"],
    correctIndex: 1,
    difficulty: 8,
    note: "Váh ústi pri Komárne, Hron pri Štúrove. Nitra sa vlieva do Váhu — trojitá pasca v pub kvíze o slovenských riekach.",
    tags: ["geografia", "slovensko"],
  },
  {
    id: "bank-187",
    body: "Ktorý alkohol je základom koktailu Moscow Mule spolu s ginger beer a limetkou?",
    answer: "Vodka",
    options: ["Vodka", "Gin", "Rum", "Tequila", "Whiskey", "Brandy"],
    correctIndex: 0,
    difficulty: 6,
    note: "Názov láká na Rusko, ale Moscow Mule = vodka + zázvorové pivo. Gin = Gin Buck, rum = Dark 'n' Stormy.",
    tags: ["alkohol", "koktaily"],
  },
  {
    id: "bank-188",
    body: "V ktorom švajčiarskom meste sídli organizácia CERN?",
    answer: "Meyrin pri Ženeve",
    options: ["Zürich", "Bern", "Meyrin pri Ženeve", "Basel", "Lugano", "Lausanne"],
    correctIndex: 2,
    difficulty: 8,
    note: "CERN = francúzsko-švajčiarska hranica pri Ženeve, administratíva v Meyrine. Tipuje sa Bern (hlavné mesto) alebo Zürich (banky).",
    tags: ["technológia", "švajčiarsko"],
  },
  {
    id: "bank-189",
    body: "Ktorý český skladateľ zložil cyklus Slovanské tance?",
    answer: "Antonín Dvořák",
    options: ["Bedřich Smetana", "Antonín Dvořák", "Leoš Janáček", "Bohuslav Martinů", "Josef Suk", "Zdeněk Fibich"],
    correctIndex: 1,
    difficulty: 7,
    note: "Smetana má Má vlast, Janáček opery. Slovanské tance (1878+) = Dvořák — pub pasca je tipovať Smetanu.",
    tags: ["hudba", "česko"],
  },
  {
    id: "bank-190",
    body: "Ktorá krajina má najvyšší počet pamiatok UNESCO na km² (hustota)?",
    answer: "Malta",
    options: ["Taliansko", "Malta", "Grécko", "Španielsko", "Francúzsko", "Portugalsko"],
    correctIndex: 1,
    difficulty: 9,
    note: "Taliansko má najviac lokalít celkovo, ale Malta je maličká a má 3 lokality — rekordná hustota na km².",
    tags: ["geografia", "malta"],
  },
  {
    id: "bank-191",
    body: "Kto je autorom textu slovenskej štátnej hymny Nad Tatrou sa blýska?",
    answer: "Janko Matúška",
    options: ["Janko Matúška", "Janko Kráľ", "Samuel Tomášik", "Pavol Országh Hviezdoslav", "Ján Hollý", "Andrej Sládkovič"],
    correctIndex: 0,
    difficulty: 8,
    note: "Tomášik napísal Hej, Slováci (iná hymna). Matúška = text Nad Tatrou (1844), melódia z folk songu.",
    tags: ["hudba", "slovensko"],
  },
  {
    id: "bank-192",
    body: "Ktoré zviera má v ríši živočíchov najväčšie oko (priemer až 27 cm)?",
    answer: "Obrovský kalmar (colossal squid)",
    options: ["Modrá veľryba", "Obrovský kalmar (colossal squid)", "Slon africký", "Pštros", "Veľryba modrá", "Morský vták"],
    correctIndex: 1,
    difficulty: 9,
    note: "Veľryba je najväčší cicavec, ale oko colossal squida je rekordné — v tme hlbín potrebuje obrovskú sosku.",
    tags: ["zvieratá", "hlbiny"],
  },
  {
    id: "bank-193",
    body: "Ktorá slovenská obec je známa baníctvom medi a je súčasťou baníckeho regiónu Špania Dolina?",
    answer: "Špania Dolina",
    options: ["Banská Štiavnica", "Špania Dolina", "Kremnica", "Rožňava", "Gelnica", "Smolník"],
    correctIndex: 1,
    difficulty: 8,
    note: "Štiavnica = striebro, Kremnica = zlato. Špania Dolina = medené bane v Nízkych Tatrách, menej známa pub otázka.",
    tags: ["história", "slovensko"],
  },
  {
    id: "bank-194",
    body: "V ktorom roku predstavil Steve Jobs prvý iPhone?",
    answer: "2007",
    options: ["2005", "2006", "2007", "2008", "2009", "2010"],
    correctIndex: 2,
    difficulty: 6,
    note: "Keynote 9. januára 2007, v predaji od júna. 2008 = iPhone 3G — pub pasca je posunúť o rok.",
    tags: ["technológia", "apple"],
  },
  {
    id: "bank-195",
    body: "Ktorý grécky hrdina usekol hlavu Medúze s pomocou štítu ako zrkadla?",
    answer: "Perseus",
    options: ["Herakles", "Perseus", "Thézeus", "Achilles", "Odysseus", "Jason"],
    correctIndex: 1,
    difficulty: 6,
    note: "Herakles mal 12 prác, Thézeus Minotaura. Perseus + Athena + zrkadlo = Medúza.",
    tags: ["mýty", "grécko"],
  },
  {
    id: "bank-196",
    body: "Ktorá rieka tečie cez centrum Prahy a pod Karlovým mostom?",
    answer: "Vltava",
    options: ["Labe", "Vltava", "Morava", "Ohře", "Berounka", "Sázava"],
    correctIndex: 1,
    difficulty: 6,
    note: "Labe tečie cez Ústí nad Labem, nie cez Prahu. Vltava = Karlov most, Pražský hrad, Národní divadlo.",
    tags: ["geografia", "česko"],
  },
  {
    id: "bank-197",
    body: "Ktorý slovenský futbalový klub vyhral najviac titulov v slovenskej lige od sezóny 1993/94?",
    answer: "MŠK Žilina",
    options: ["Slovan Bratislava", "MŠK Žilina", "Inter Bratislava", "Spartak Trnava", "Trenčín", "DAC Dunajská Streda"],
    correctIndex: 1,
    difficulty: 8,
    note: "Slovan je najslávnejší historicky, ale od 1993 Žilina vedie v počte titulov — pub pasca je tipovať Slovan.",
    tags: ["šport", "slovensko"],
  },
  {
    id: "bank-198",
    body: "Ktoré zviera je logom Svetového fondu na ochranu prírody (WWF)?",
    answer: "Panda veľká",
    options: ["Tiger", "Panda veľká", "Lev", "Gorila", "Delfín", "Orangutan"],
    correctIndex: 1,
    difficulty: 6,
    note: "WWF logo od 1961 — čierno-biela panda. Tiger WWF používa v kampaniach, nie v logu.",
    tags: ["zvieratá", "ekológia"],
  },
  {
    id: "bank-199",
    body: "V ktorom filme figuruje kanibal Dr. Hannibal Lecter, ktorý hrá Anthony Hopkins?",
    answer: "Mlčanie jahniatok",
    options: ["Psycho", "Mlčanie jahniatok", "Siedem", "Saw", "Zodiac", "American Psycho"],
    correctIndex: 1,
    difficulty: 6,
    note: "Psycho = Norman Bates, Siedem = John Doe. Lecter + Clarice = Silence of the Lambs (1991).",
    tags: ["film", "horor"],
  },
  {
    id: "bank-200",
    body: "Z ktorej krajiny pochádza tradičné jedlo paella?",
    answer: "Španielsko",
    options: ["Taliansko", "Španielsko", "Portugalsko", "Francúzsko", "Grécko", "Mexiko"],
    correctIndex: 1,
    difficulty: 6,
    note: "Valencia = kolíska paelly. Taliansko má risotto — podobná ryža, iná krajina.",
    tags: ["jedlo", "španielsko"],
  },
  {
    id: "bank-201",
    body: "Ktorý slovenský hokejový útočník prekonal v NHL hranicu 500 gólov ako prvý Slovák?",
    answer: "Miroslav Šatan",
    options: ["Peter Šťastný", "Miroslav Šatan", "Marián Hossa", "Miroslav Iglódy", "Richard Zedník", "Tomáš Tatar"],
    correctIndex: 1,
    difficulty: 8,
    note: "Šťastný skončil na 454 góloch. Šatan prekonal 500 — pub pasca je tipovať Šťastného kvôli sláve.",
    tags: ["šport", "slovensko"],
  },
  {
    id: "bank-202",
    body: "Ktorá krajina vyrobila ako prvá komerčný audio CD prehrávač (Sony CDP-101, 1982)?",
    answer: "Japonsko",
    options: ["USA", "Nemecko", "Japonsko", "Holandsko", "Južná Kórea", "Švédsko"],
    correctIndex: 2,
    difficulty: 8,
    note: "Philips vyvinul technológiu v Holandsku, ale prvý spotrebný prehrávač Sony v Japonsku. Tipuje sa Philips/Holandsko.",
    tags: ["technológia", "japonsko"],
  },
  {
    id: "bank-203",
    body: "Ktorý český spisovateľ napísal antiutopický román Válka s mloky?",
    answer: "Karel Čapek",
    options: ["Jaroslav Hašek", "Karel Čapek", "Milan Kundera", "Bohumil Hrabal", "Ladislav Fuks", "Ivan Klíma"],
    correctIndex: 1,
    difficulty: 8,
    note: "Čapek = R.U.R. (roboti) aj Mloky (1936). Hašek = Švejk — obaja bratia Čapkovci v pub kvíze.",
    tags: ["literatúra", "česko"],
  },
  {
    id: "bank-204",
    body: "Ktoré mesto je známe vežou Pisa, ktorá sa naklonila už počas výstavby v 12. storočí?",
    answer: "Pisa",
    options: ["Rím", "Florencia", "Pisa", "Benátky", "Miláno", "Neapol"],
    correctIndex: 2,
    difficulty: 6,
    note: "Campanile pri katedrále v Pise — nie veža v Ríme ani Florencii. Pub otázka s jasnou pascou Benátky.",
    tags: ["architektúra", "taliansko"],
  },
  {
    id: "bank-205",
    body: "Ktorý alkohol je hlavnou zložkou tradičného írskeho drinku Irish Coffee?",
    answer: "Írska whiskey",
    options: ["Rum", "Írska whiskey", "Brandy", "Gin", "Vodka", "Tequila"],
    correctIndex: 1,
    difficulty: 6,
    note: "Horúca káva + whiskey + cukor + smotana. Rum = grog, brandy = French coffee variant.",
    tags: ["alkohol", "írsko"],
  },
  {
    id: "bank-206",
    body: "Ktorá televízna relácia sa odohráva vo fiktívnom meste Springfield a má postavu Homera Simpsona?",
    answer: "Simpsonovci",
    options: ["Futurama", "Simpsonovci", "Family Guy", "South Park", "American Dad", "Bob's Burgers"],
    correctIndex: 1,
    difficulty: 6,
    note: "Futurama = tiež Matt Groening, ale v budúcnosti. Springfield existuje vo viacerých štátoch — ikonická pub otázka.",
    tags: ["televízia", "animácia"],
  },
  {
    id: "bank-207",
    body: "Ktorý slovenský štátny symbol — dvojkríž na trojvrchu — bol schválený ústavným zákonom v roku 1992?",
    answer: "Erb Slovenskej republiky",
    options: ["Vlajka SR", "Erb Slovenskej republiky", "Hymna SR", "Pečať prezidenta", "Ústava SR", "Tlakovka"],
    correctIndex: 1,
    difficulty: 8,
    note: "Vlajka schválená tiež 1992, ale otázka cieli na erb (linden, Tatry, dvojkríž). Tipuje sa vlajka.",
    tags: ["politika", "slovensko"],
  },
  {
    id: "bank-208",
    body: "Ktorá hra od Valve má postavy CT a T a mapu Dust2?",
    answer: "Counter-Strike",
    options: ["Counter-Strike", "Half-Life", "Team Fortress 2", "Call of Duty", "Battlefield", "Valorant"],
    correctIndex: 0,
    difficulty: 6,
    note: "Half-Life = singleplayer, CS pôvodne mod. Dust2 = najhranejšia mapa v histórii FPS.",
    tags: ["hry", "esport"],
  },
  {
    id: "bank-209",
    body: "Ktorý český panovník dal postaviť Karlův most v Prahe (pôvodne Kamenný most)?",
    answer: "Karel IV.",
    options: ["Václav I.", "Karel IV.", "Rudolf II.", "Přemysl Otakar II.", "Václav IV.", "Jiří z Poděbrad"],
    correctIndex: 1,
    difficulty: 7,
    note: "Most zahájený 1357 za Karla IV. Rudolf II. = alchymia na Pražskom hrade, nie most.",
    tags: ["história", "česko"],
  },
  {
    id: "bank-210",
    body: "Ktorý slovenský básnik napísal báseň Hrobka v Kremnických vrchoch?",
    answer: "Andrej Sládkovič",
    options: ["Pavol Országh Hviezdoslav", "Andrej Sládkovič", "Ján Hollý", "Samo Chalupka", "Janko Kráľ", "Pavol Országh-Veselý"],
    correctIndex: 1,
    difficulty: 8,
    note: "Sládkovič = Marína aj Hrobka. Hviezdoslav má Mor ho! — v pub kvíze sa zamieňajú romantici.",
    tags: ["literatúra", "slovensko"],
  },
  {
    id: "bank-211",
    body: "V ktorom roku bol spustený prvý verejný webový server CERNu a tým aj World Wide Web pre verejnosť?",
    answer: "1991",
    options: ["1989", "1990", "1991", "1993", "1995", "1997"],
    correctIndex: 2,
    difficulty: 9,
    note: "Tim Berners-Lee navrhol WWW 1989, prvý server info.cern.ch verejne 1991. Mosaic browser až 1993.",
    tags: ["internet", "história"],
  },
];